Repository symfony/ux, pull requests merged in 2024-03, with the labels that each got.

#1561 [Live] Improving child render handling: avoid removing element from DOM when possible
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/morphdom.ts
  src/LiveComponent/assets/test/controller/child.test.ts
  src/LiveComponent/assets/test/tools.ts
Labels: Status: Needs Review

#1563 [CI] Upgrade ramsey/composer-install
  .github/workflows/test-turbo.yml
  .github/workflows/test.yaml
  .github/workflows/ux.symfony.com.yaml
Labels: Status: Reviewed

#1568 [Doc] Minor fix in a Live Component code example
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1560 [Site] Upgrade 2.16
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/templates/components/FoodVote.html.twig
  ux.symfony.com/templates/components/InlineEditFood.html.twig
  ux.symfony.com/templates/components/InvoiceCreator.html.twig
  ux.symfony.com/templates/components/InvoiceCreatorLineItem.html.twig
  ux.symfony.com/templates/components/LiveMemory/Board.html.twig
  ux.symfony.com/templates/components/LiveMemory/Card.html.twig
  ux.symfony.com/templates/components/LiveMemory/Score.html.twig
  ux.symfony.com/templates/components/NewCategoryForm.html.twig
  ux.symfony.com/templates/components/NewProductForm.html.twig
  ux.symfony.com/templates/components/RegistrationForm.html.twig
  ux.symfony.com/templates/components/UploadFiles.html.twig
Labels: Status: Needs Review

#1564 Update CVA docs and fixes
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1580 [TwigComponent] fix typo in compoundVariants documentation
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed

#1578 [LiveMemory] Regroup files & fix performances issues
  ux.symfony.com/assets/styles/demos/live-memory.min.css
  ux.symfony.com/assets/styles/demos/live-memory/app/_html.scss
  ux.symfony.com/assets/styles/demos/live-memory/app/_reset.scss
  ux.symfony.com/assets/styles/demos/live-memory/app/_root.scss
  ux.symfony.com/assets/styles/demos/live-memory/app/_themes.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Board.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Card.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Header.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Overlay.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Score.scss
  ux.symfony.com/config/packages/twig.yaml
  ux.symfony.com/config/packages/twig_component.yaml
  ux.symfony.com/src/LiveMemory/Component/Board.php
  ux.symfony.com/src/LiveMemory/Component/Icon.php
  ux.symfony.com/src/LiveMemory/Component/ScoreRow.php
  ux.symfony.com/src/LiveMemory/Component/Timer.php
  ux.symfony.com/src/LiveMemory/GameLevels.php
  ux.symfony.com/templates/components/LiveMemory/Card.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Board.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Card.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Icon.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Logo.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Metric.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Metrics.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Score.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/ScoreRow.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Tableau.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/ThemeSwitch.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Timer.html.twig
  ux.symfony.com/templates/demos/live_memory/index.html.twig
Labels: Status: Needs Review

#1575 CVA apply function accept null arguments
  src/TwigComponent/src/CVA.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1571 [TwigComponent] attributes.has() method
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed

#1507 [LiveComponent] Add modifier option to LiveProp
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/Attribute/LiveProp.php
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/EventListener/QueryStringInitializeSubscriber.php
  src/LiveComponent/src/LiveComponentHydrator.php
  src/LiveComponent/src/Metadata/LiveComponentMetadata.php
  src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php
  src/LiveComponent/src/Metadata/LivePropMetadata.php
  src/LiveComponent/src/Util/LiveControllerAttributesCreator.php
  src/LiveComponent/src/Util/QueryStringPropsExtractor.php
  src/LiveComponent/tests/Fixtures/Component/ComponentWithUrlBoundProps.php
  src/LiveComponent/tests/Fixtures/templates/components/component_with_url_bound_props.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_component_with_url_bound_props.html.twig
  src/LiveComponent/tests/Functional/EventListener/AddLiveAttributesSubscriberTest.php
  src/LiveComponent/tests/Functional/EventListener/QueryStringInitializerSubscriberTest.php
  src/LiveComponent/tests/Functional/Metadata/LiveComponentMetadataFactoryTest.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
  src/LiveComponent/tests/Unit/Metadata/LiveComponentMetadataTest.php
  src/LiveComponent/tests/Unit/Metadata/LivePropMetadataTest.php
Labels: Status: Needs Review

#1583 [LiveComponent] Fix collections hydration with serializer
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/src/LiveComponentHydrator.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
Labels: Status: Needs Review

#1579 [TwigComponent] Register safe classes in the configurator
  src/LiveComponent/src/Attribute/LiveProp.php
  src/TwigComponent/src/BlockStack.php
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/src/ComponentRenderer.php
  src/TwigComponent/src/Test/InteractsWithTwigComponents.php
  src/TwigComponent/src/Twig/TemplateNameParser.php
  src/TwigComponent/src/Twig/TwigEnvironmentConfigurator.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
  ux.symfony.com/src/LiveMemory/Component/ScoreRow.php
  ux.symfony.com/src/LiveMemory/Component/Timer.php
Labels: Status: Needs Review

#1515 [LiveComponent] Lazy load LiveComponent
  UPGRADE.md
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/assets/dist/Component/plugins/LazyPlugin.d.ts
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Component/plugins/LazyPlugin.ts
  src/LiveComponent/assets/src/live_controller.ts
  src/LiveComponent/assets/test/dom_utils.test.ts
  src/LiveComponent/assets/test/tools.ts
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/EventListener/DeferLiveComponentSubscriber.php
  src/LiveComponent/templates/deferred.html.twig
  src/LiveComponent/tests/Fixtures/Component/TallyComponent.php
  src/LiveComponent/tests/Fixtures/templates/components/tally_component.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_deferred_component.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_deferred_component_with_li_tag.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_deferred_component_with_placeholder.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_deferred_component_with_template.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_lazy_component.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_lazy_component_with_value.html.twig
  src/LiveComponent/tests/Functional/EventListener/DeferLiveComponentSubscriberTest.php
  src/LiveComponent/tests/Unit/EventListener/DeferLiveComponentSubscriberTest.php
  yarn.lock
Labels: Status: Needs Review

#1450 [Icons] Introduce `symfony/ux-icons`
  src/Icons/.gitattributes
  src/Icons/.gitignore
  src/Icons/.symfony.bundle.yaml
  src/Icons/LICENSE
  src/Icons/README.md
  src/Icons/composer.json
  src/Icons/config/asset_mapper.php
  src/Icons/config/iconify.php
  src/Icons/config/services.php
  src/Icons/config/twig_component.php
  src/Icons/doc/index.rst
  src/Icons/phpunit.xml.dist
  src/Icons/src/Command/ImportIconCommand.php
  src/Icons/src/Command/WarmCacheCommand.php
  src/Icons/src/DependencyInjection/UXIconsExtension.php
  src/Icons/src/EventListener/WarmIconCacheOnAssetCompileListener.php
  src/Icons/src/Exception/IconNotFoundException.php
  src/Icons/src/IconCacheWarmer.php
  src/Icons/src/IconRegistryInterface.php
  src/Icons/src/IconRenderer.php
  src/Icons/src/Iconify.php
  src/Icons/src/Registry/CacheIconRegistry.php
  src/Icons/src/Registry/ChainIconRegistry.php
  src/Icons/src/Registry/IconifyOnDemandRegistry.php
  src/Icons/src/Registry/LocalSvgIconRegistry.php
  src/Icons/src/Svg/Icon.php
  src/Icons/src/Twig/IconFinder.php
  src/Icons/src/Twig/UXIconComponent.php
  src/Icons/src/Twig/UXIconComponentListener.php
  src/Icons/src/Twig/UXIconExtension.php
  src/Icons/src/UXIconsBundle.php
  src/Icons/tests/Fixtures/TestKernel.php
  src/Icons/tests/Fixtures/icons/sub/check.svg
  src/Icons/tests/Fixtures/icons/user.svg
  src/Icons/tests/Fixtures/svg/invalid1.svg
  src/Icons/tests/Fixtures/svg/invalid2.svg
  src/Icons/tests/Fixtures/svg/invalid3.svg
  src/Icons/tests/Fixtures/svg/invalid4.svg
  src/Icons/tests/Fixtures/svg/valid1.svg
  src/Icons/tests/Fixtures/svg/valid2.svg
  src/Icons/tests/Fixtures/svg/valid3.svg
  src/Icons/tests/Fixtures/svg/valid4.svg
  src/Icons/tests/Fixtures/svg/valid5.svg
  src/Icons/tests/Fixtures/templates/template1.html.twig
  src/Icons/tests/Fixtures/templates/template2.html.twig
  src/Icons/tests/Integration/Command/ImportIconCommandTest.php
  src/Icons/tests/Integration/Command/WarmCacheCommandTest.php
  src/Icons/tests/Integration/RenderIconsInTwigTest.php
  src/Icons/tests/Unit/Registry/LocalSvgIconRegistryTest.php
  src/Icons/tests/Unit/Svg/IconTest.php
  src/Icons/tests/bootstrap.php
Labels: Status: Needs Review

#1595 [Icons] Allow disabling the "on demand" system
  src/Icons/doc/index.rst
  src/Icons/src/DependencyInjection/UXIconsExtension.php
Labels: Status: Needs Review

#1599 [Icons] Fix Kernel deprecation
  src/Icons/tests/Fixtures/TestKernel.php
Labels: Status: Reviewed

#1597 [Icons] Add InMemory registry to allow easier tests
  src/Icons/src/Registry/InMemoryIconRegistry.php
  src/Icons/tests/Unit/Registry/InMemoryIconRegistryTest.php
Labels: Status: Needs Review

#1594 [Icons] Improve cache warmup by looking at every string
  src/Icons/config/iconify.php
  src/Icons/doc/index.rst
  src/Icons/src/Command/WarmCacheCommand.php
  src/Icons/src/DependencyInjection/UXIconsExtension.php
  src/Icons/src/Iconify.php
  src/Icons/src/Twig/IconFinder.php
  src/Icons/tests/Fixtures/templates/template2.html.twig
  src/Icons/tests/Integration/Command/WarmCacheCommandTest.php
Labels: Status: Needs Review

#1607 [Icons] Compute viewBox with iconset data (+tests)
  src/Icons/src/Iconify.php
  src/Icons/tests/Unit/IconifyTest.php
Labels: Status: Reviewed

#1600 CVA: Allow array for base, variants and compound
  src/TwigComponent/src/CVA.php
  src/TwigComponent/src/Twig/ComponentExtension.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1608 [Icons] Rework cache warm
  src/Icons/config/services.php
  src/Icons/src/DependencyInjection/UXIconsExtension.php
  src/Icons/src/Twig/IconFinder.php
Labels: Status: Reviewed

#1603 [Icon] Console theme: reference the webite + improve icon readability
  src/Icons/src/Command/ImportIconCommand.php
  src/Icons/tests/Integration/Command/ImportIconCommandTest.php
Labels: Status: Reviewed

#1606 [Icons] Test IconRenderer
  src/Icons/src/IconRenderer.php
  src/Icons/tests/Integration/RenderIconsInTwigTest.php
  src/Icons/tests/Unit/IconRendererTest.php
  src/Icons/tests/Unit/Registry/InMemoryIconRegistryTest.php
  src/Icons/tests/Util/InMemoryIconRegistry.php
Labels: Status: Reviewed

#1610 [Twig] allow compound variant value to be string
  src/TwigComponent/src/CVA.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1635 [Doc] Update the UX icons documentation
  src/Icons/doc/index.rst
Labels: documentation, Status: Reviewed

#1634 [Doc] Fixed the name of an RST directive
  src/LiveComponent/doc/index.rst
Labels: documentation, Status: Reviewed

#1621 [TwigComponent] Fix typo in the documentation
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed

#1609 [Twig] allow stringable objects as attribute values
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed

#1605 [Chart.js] add view-value-change event
  src/Chartjs/CHANGELOG.md
  src/Chartjs/assets/dist/controller.js
  src/Chartjs/assets/src/controller.ts
  src/Chartjs/assets/test/controller.test.ts
Labels: Status: Reviewed

#1593 [LiveComponent] Throw exception for typed LiveProps as interfaces
  src/LiveComponent/src/LiveComponentHydrator.php
  src/LiveComponent/tests/Fixtures/Dto/SimpleDto.php
  src/LiveComponent/tests/Fixtures/Dto/SimpleDtoInterface.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
Labels: Status: Reviewed

#1637 [Site][LiveComponent] cs fixes and cleanup
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
  ux.symfony.com/src/Controller/Icons/IconsController.php
  ux.symfony.com/src/Model/Icon/Icon.php
  ux.symfony.com/src/Service/Icon/IconSetRepository.php
  ux.symfony.com/src/Service/Icon/Iconify.php
  ux.symfony.com/src/Twig/Components/Icon/IconSearch.php
  ux.symfony.com/src/Twig/Components/Icon/IconSetCard.php
  ux.symfony.com/tests/Functional/IconsTest.php
Labels: Status: Reviewed

#1638 [Autocomplete] Fix tests for ORM 3.0
  src/Autocomplete/src/Doctrine/EntityMetadata.php
  src/Autocomplete/tests/Fixtures/Kernel.php
  src/Autocomplete/tests/Integration/Doctrine/EntityMetadataTest.php
Labels: Status: Reviewed

#1631 [LiveComponent] Fix idiomorph dependency (fix #1567)
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/package.json
  yarn.lock
Labels: Status: Reviewed

#1592 [Site] Fix mobile menu
  ux.symfony.com/assets/controllers/ux-header-controller.js
  ux.symfony.com/assets/styles/components/_PackageBox.scss
  ux.symfony.com/assets/styles/sections/_header.scss
  ux.symfony.com/assets/styles/sections/_nav.scss
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/_nav.html.twig
Labels: Status: Reviewed

#1617 [Icons] Add Icon + Iconify tests
  src/Icons/src/DependencyInjection/UXIconsExtension.php
  src/Icons/src/Iconify.php
  src/Icons/src/Svg/Icon.php
  src/Icons/tests/Fixtures/Iconify/collections.json
  src/Icons/tests/Fixtures/Iconify/icon.json
  src/Icons/tests/Fixtures/Iconify/icon.svg
  src/Icons/tests/Unit/IconifyTest.php
  src/Icons/tests/Unit/Svg/IconTest.php
Labels: Status: Needs Review

#1641 [Doc] Tweaks and fixes for UX Icons docs
  src/Icons/doc/index.rst
Labels: documentation, Status: Reviewed

#1645 [Doc] Fix some syntax issues in Typed docs
  src/Typed/doc/index.rst
Labels: Status: Reviewed

#1644 [Doc] Fix a minor issue in Vue docs
  src/Vue/doc/index.rst
Labels: documentation, Status: Needs Review

#1615 [Doc] Clarify collection hydration requirements
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1405 [Twig] Allow nested attributes
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Fixtures/templates/components/JustAttributes.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/NestedAttributes.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed, Status: Waiting Feedback, Feature

#1584 [DX] Show component name in multiple elements error
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Component/index.ts
Labels: Status: Reviewed

#1654 [Icons] Update demo URL
  src/Icons/README.md
Labels: Status: Reviewed

#1659 [Icons] Accept <twig:ux:icon /> (lowercase)
  src/Icons/src/Twig/UXIconComponentListener.php
  src/Icons/tests/Fixtures/templates/template1.html.twig
Labels: Status: Reviewed

#1602 [Icons] Some doc updates
  src/Icons/README.md
  src/Icons/doc/index.rst
Labels: Status: Reviewed

#1661 [CI] Freeze Foundry 1.37
  src/Autocomplete/composer.json
  src/LiveComponent/composer.json
Labels: Status: Reviewed

#1664 [Doc] Misc updates in the StimulusBundle docs
  src/StimulusBundle/doc/index.rst
Labels: documentation, Status: Reviewed

#1662 Remove experimental tag to HTML syntax
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed
