Repository symfony/ux, pull requests merged in 2024-07, with the labels that each got.

#1947 [Site] Update vendors
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/services.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Controller/UxPackage/CropperjsController.php
  ux.symfony.com/src/Twig/Icon.php
  ux.symfony.com/templates/_meta.html.twig
Labels: Status: Needs Review, Site

#1955 [Site] Fix Chart.js script in importmap
  ux.symfony.com/composer.lock
  ux.symfony.com/importmap.php
Labels: Status: Needs Review, Site

#1956 [Site] Fix error page
  ux.symfony.com/templates/bundles/TwigBundle/Exception/error.html.twig
Labels: Status: Needs Review, Site

#1957 [LiveComponent] Fix (de)hydration of composite and/or foreign ID entities
  src/LiveComponent/src/Hydration/DoctrineEntityHydrationExtension.php
  src/LiveComponent/tests/Fixtures/Entity/CompositeIdEntity.php
  src/LiveComponent/tests/Fixtures/Entity/ForeignKeyIdEntity.php
  src/LiveComponent/tests/Fixtures/Factory/CompositeIdEntityFactory.php
  src/LiveComponent/tests/Fixtures/Factory/ForeignKeyIdEntityFactory.php
  src/LiveComponent/tests/Integration/Hydration/DoctrineEntityHydrationExtensionTest.php
Labels: Bug, Status: Reviewed, LiveComponent

#1966 [TwigComponent] Allow @ prefix in nested attributes
  src/TwigComponent/src/Twig/TwigPreLexer.php
  src/TwigComponent/tests/Unit/TwigPreLexerTest.php
Labels: Status: Needs Review, TwigComponent

#1960 [TwigComponent] allow attributes to be prefixed with `@`
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Bug, Status: Needs Review, TwigComponent

#1951 [Dropzone] Remove event listeners on disconnect
  src/Dropzone/assets/dist/controller.d.ts
  src/Dropzone/assets/dist/controller.js
  src/Dropzone/assets/src/controller.ts
Labels: Bug, Status: Reviewed, Dropzone

#1965 Disable cache warmup when translator is identity translator
  src/Translator/doc/index.rst
  src/Translator/src/DependencyInjection/TranslatorCompilerPass.php
  src/Translator/src/UxTranslatorBundle.php
  src/Translator/tests/Kernel/FrameworkAppKernel.php
  src/Translator/tests/UxTranslatorBundleTest.php
Labels: Bug, Status: Reviewed

#1889 [Icons] Expose IconRendererInterface
  src/Icons/config/services.php
  src/Icons/src/IconRenderer.php
  src/Icons/src/IconRendererInterface.php
  src/Icons/src/Twig/UXIconComponentListener.php
  src/Icons/tests/Integration/IconRendererTest.php
Labels: Status: Reviewed, Feature, Icons

#1974 Update index.rst
  src/React/doc/index.rst
Labels: documentation, Status: Reviewed, React

#1977 [Doc] Minor syntax fixes in the Twig component docs
  src/TwigComponent/doc/index.rst
Labels: documentation, Status: Reviewed

#1985 Fix wrong example for HTML syntax
  src/TwigComponent/doc/index.rst
Labels: documentation, Status: Reviewed

#1994 [Icon] Emphasis HTML syntax requires TwigComponent
  src/Icons/doc/index.rst
Labels: documentation, Status: Reviewed, Icons

#1989 fix null props not overwrite parent context
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/tests/Fixtures/templates/anonymous_component_with_props_overwrite_parents_props.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/Alert.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/Icon.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Bug, Status: Reviewed

#1983 [Site] Leverage PHP-CS-Fixer parralel runner
  ux.symfony.com/.php-cs-fixer.dist.php
Labels: Status: Needs Review, Site

#1988 Fix random errors are throw when empty props
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/tests/Fixtures/templates/anonymous_component_with_empty_props.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/EmptyProps.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Bug, Status: Reviewed, TwigComponent

#1991 [Doc] Mention that boolean properties require the dynamic syntax
  src/TwigComponent/doc/index.rst
Labels: documentation, Status: Reviewed

#1996 [Translator] Fix CS on TranslatorCompilerPass
  src/Translator/src/DependencyInjection/TranslatorCompilerPass.php
Labels: Bug, Status: Reviewed, Feature

#1967 [LazyImage] Webperfs and LCP considerations
  src/LazyImage/doc/index.rst
Labels: documentation, Status: Reviewed, LazyImage

#1928 docs: fix mercure config-file
  src/Turbo/CONTRIBUTING.md
Labels: Status: Reviewed

#1987 chore(typescript): upgrade target from es2017 to es2021
  src/Autocomplete/assets/dist/controller.js
  src/LiveComponent/assets/dist/live_controller.js
  src/Svelte/assets/dist/render_controller.js
  src/Translator/assets/dist/translator_controller.js
  src/Vue/assets/dist/render_controller.js
  tsconfig.json
Labels: Status: Reviewed

#1948 [Site] Custom TwigCsFixer config
  ux.symfony.com/.twig-cs-fixer.dist.php
  ux.symfony.com/templates/components/Code/CodeLine.html.twig
  ux.symfony.com/templates/ux_packages/turbo.html.twig
  ux.symfony.com/templates/ux_packages/turbo/_chat_form.html.twig
  ux.symfony.com/templates/ux_packages/turbo/_chat_list.html.twig
  ux.symfony.com/templates/ux_packages/turbo/_chat_message_count.html.twig
  ux.symfony.com/templates/ux_packages/turbo/all_users_chat_success.stream.html.twig
  ux.symfony.com/templates/ux_packages/turbo/chat_success.stream.html.twig
Labels: Status: Needs Review, Site

#1980 [Live] Fix 'onUpdated' hook call
  src/LiveComponent/src/LiveComponentHydrator.php
  src/LiveComponent/tests/Fixtures/Component/WithOnUpdated.php
  src/LiveComponent/tests/Fixtures/templates/components/with_on_updated.html.twig
  src/LiveComponent/tests/Functional/Test/InteractsWithLiveComponentsTest.php
Labels: Bug, Status: Reviewed

#1946 [LiveComponent] Add 'live_action' twig function
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/composer.json
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/Twig/LiveComponentExtension.php
  src/LiveComponent/src/Twig/LiveComponentRuntime.php
  src/LiveComponent/tests/Fixtures/Kernel.php
  src/LiveComponent/tests/Unit/Twig/LiveComponentRuntimeTest.php
Labels: Status: Reviewed, Feature, LiveComponent, DX

#2016 chore(ux.symfony.com:deps) update Twig-CS-Fixer to ^3.0
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
Labels: Status: Reviewed, DX

#1702 [LiveComponent] Document how to use `extra_options` in the Ajax-powered autocomplete
  src/Autocomplete/doc/index.rst
Labels: Status: Reviewed

#1826 Introduce cookbook documentation
  ux.symfony.com/assets/images/cookbook/component_architecture.png
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_Cookbook.scss
  ux.symfony.com/composer.lock
  ux.symfony.com/config/services.yaml
  ux.symfony.com/cookbook/architecture_component.md
  ux.symfony.com/src/Controller/CookbookController.php
  ux.symfony.com/src/Model/Cookbook.php
  ux.symfony.com/src/Service/CommonMark/ConverterFactory.php
  ux.symfony.com/src/Service/CookbookFactory.php
  ux.symfony.com/src/Service/CookbookParser.php
  ux.symfony.com/src/Service/CookbookRepository.php
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/components/Card.html.twig
  ux.symfony.com/templates/components/Cookbook.html.twig
  ux.symfony.com/templates/cookbook/index.html.twig
  ux.symfony.com/templates/cookbook/show.html.twig
Labels: Status: Needs Review, Feature
