Repository symfony/ux, pull requests merged in 2024-10, with the labels that each got.

#2226 [UX Icons] Some updates in the full configuration example docs
  src/Icons/doc/index.rst
Labels: docs, Status: Reviewed, Icons

#2229 Update index.rst
  src/Map/doc/index.rst
Labels: Bug, docs, Status: Needs Review, Map

#2231 [Twig][Icons][Map] fix wiring of `ComponentRuntime`
  src/Icons/config/services.php
  src/Map/config/services.php
  src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php
Labels: Bug, Status: Reviewed, Icons, TwigComponent, Map

#2196 [Turbo] Add Helper/TurboStream::append() et al. methods
  src/Turbo/CHANGELOG.md
  src/Turbo/doc/index.rst
  src/Turbo/phpstan.neon.dist
  src/Turbo/src/Helper/TurboStream.php
  src/Turbo/src/TurboStreamResponse.php
  src/Turbo/tests/Helper/TurboStreamTest.php
  src/Turbo/tests/app/Kernel.php
Labels: Status: Reviewed, Feature, Turbo

#2227 Add `<twig:Turbo:Stream:*>` components
  .github/workflows/test-turbo.yml
  src/Turbo/CHANGELOG.md
  src/Turbo/composer.json
  src/Turbo/templates/components/Stream/After.html.twig
  src/Turbo/templates/components/Stream/Append.html.twig
  src/Turbo/templates/components/Stream/Before.html.twig
  src/Turbo/templates/components/Stream/Prepend.html.twig
  src/Turbo/templates/components/Stream/Refresh.html.twig
  src/Turbo/templates/components/Stream/Remove.html.twig
  src/Turbo/templates/components/Stream/Replace.html.twig
  src/Turbo/templates/components/Stream/Update.html.twig
  src/Turbo/tests/app/Kernel.php
  src/Turbo/tests/app/templates/broadcast/Artist.stream.html.twig
  src/Turbo/tests/app/templates/broadcast/Book.stream.html.twig
  src/Turbo/tests/app/templates/broadcast/Song.stream.html.twig
  src/Turbo/tests/app/templates/chat/message.stream.html.twig
  src/Turbo/tests/app/templates/form.stream.html.twig
Labels: Status: Reviewed, Feature

#2232 Replace JS toolchain by asset-mapper when testing ux-turbo
  .github/workflows/test-turbo.yml
  src/Turbo/.gitignore
  src/Turbo/composer.json
  src/Turbo/tests/BroadcastTest.php
  src/Turbo/tests/app/Kernel.php
  src/Turbo/tests/app/assets/controllers.json
  src/Turbo/tests/app/assets/controllers/.gitignore
  src/Turbo/tests/app/importmap.php
  src/Turbo/tests/app/package.json
  src/Turbo/tests/app/public/index.php
  src/Turbo/tests/app/templates/base.html.twig
  src/Turbo/tests/app/webpack.config.js
Labels: Status: Reviewed

#2235 [TwigComponent][Docs] Fix outerblock markup example
  src/TwigComponent/doc/index.rst
Labels: docs, Status: Reviewed, TwigComponent

#2239 [Site] Fix favicon
  ux.symfony.com/public/android-chrome-192x192.png
  ux.symfony.com/public/android-chrome-512x512.png
  ux.symfony.com/public/apple-touch-icon.png
  ux.symfony.com/public/favicon.ico
  ux.symfony.com/public/favicon.svg
Labels: Status: Needs Review, Site

#2237 [Site] Configure Icons + fixes
  ux.symfony.com/assets/styles/components/_Changelog.scss
  ux.symfony.com/assets/styles/components/_DocsLink.scss
  ux.symfony.com/assets/styles/components/_Icon.scss
  ux.symfony.com/assets/styles/components/_PackageBox.scss
  ux.symfony.com/composer.lock
  ux.symfony.com/config/packages/ux_icons.yaml
  ux.symfony.com/src/Twig/Components/ChangelogItem.php
  ux.symfony.com/src/UX/IconRenderer.php
  ux.symfony.com/templates/components/ChangelogItem.html.twig
  ux.symfony.com/templates/components/DocsLink.html.twig
  ux.symfony.com/templates/components/Package/PackageBox.html.twig
  ux.symfony.com/templates/components/ThemeSwitcher.html.twig
  ux.symfony.com/templates/documentation/index.html.twig
  ux.symfony.com/templates/main/_file_tree.html.twig
  ux.symfony.com/templates/ux_packages/lazy_image.html.twig
  ux.symfony.com/templates/ux_packages/live_component.html.twig
  ux.symfony.com/templates/ux_packages/swup.html.twig
Labels: Status: Reviewed, Site

#2242 Delete UPGRADE.md
  UPGRADE.md
Labels: Status: Reviewed

#2244 [Site] Remove unused PostMount method
  ux.symfony.com/src/Twig/Components/Icon/IconSearch.php
Labels: Status: Needs Review, Site

#2243 [UX] Clean .gitignore / .gitattributes (rebase + merge #1969)
  .gitignore
  src/Autocomplete/.gitattributes
  src/Autocomplete/.gitignore
  src/Chartjs/.gitattributes
  src/Chartjs/.gitignore
  src/Cropperjs/.gitattributes
  src/Cropperjs/.gitignore
  src/Dropzone/.gitattributes
  src/Dropzone/.gitignore
  src/Icons/.gitattributes
  src/Icons/.gitignore
  src/LazyImage/.gitattributes
  src/LazyImage/.gitignore
  src/LiveComponent/.gitattributes
  src/LiveComponent/.gitignore
  src/Map/.gitattributes
  src/Notify/.gitattributes
  src/Notify/.gitignore
  src/React/.gitattributes
  src/React/.gitignore
  src/StimulusBundle/.gitattributes
  src/StimulusBundle/.gitignore
  src/Svelte/.gitattributes
  src/Svelte/.gitignore
  src/Swup/.gitattributes
  src/Swup/.gitignore
  src/TogglePassword/.gitattributes
  src/TogglePassword/.gitignore
  src/Translator/.gitattributes
  src/Translator/.gitignore
  src/Turbo/.gitattributes
  src/Turbo/.gitignore
  src/Turbo/tests/app/.gitignore
  src/TwigComponent/.gitattributes
  src/TwigComponent/.gitignore
  src/Typed/.gitattributes
  src/Typed/.gitignore
  src/Vue/.gitattributes
  src/Vue/.gitignore
Labels: Status: Reviewed

#2245 [Site] Skip yarn & npm install during deploy
  ux.symfony.com/.platform.app.yaml
Labels: Status: Needs Review, Site

#2246 [Site] Skip yarn & npm install during deploy
  ux.symfony.com/.platform.app.yaml
Labels: Status: Needs Review, Site

#2154 [Dropzone] Enable file replacement via "drag-and-drop"
  src/Dropzone/CHANGELOG.md
  src/Dropzone/assets/dist/controller.d.ts
  src/Dropzone/assets/dist/controller.js
  src/Dropzone/assets/src/controller.ts
  src/Dropzone/assets/test/controller.test.ts
Labels: Status: Needs Review, Feature, Dropzone

#2253 fix: typo on Autocomplete page
  src/Autocomplete/doc/index.rst
Labels: Status: Needs Review

#2248 [Site] Add Stimulus Bundle missing page
  ux.symfony.com/assets/images/ux_packages/stimulus-1200x675.png
  ux.symfony.com/assets/images/ux_packages/stimulus.svg
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_FeatureBox.scss
  ux.symfony.com/assets/styles/sections/_hero.scss
  ux.symfony.com/config/packages/ux_icons.yaml
  ux.symfony.com/src/Controller/UxPackage/StimulusController.php
  ux.symfony.com/src/Model/UxPackage.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/src/Twig/HomepageTerminalSwapper.php
  ux.symfony.com/templates/components/FeatureBox.html.twig
  ux.symfony.com/templates/components/Package/PackageHeader.html.twig
  ux.symfony.com/templates/ux_packages/stimulus.html.twig
Labels: Status: Reviewed, Site

#2263 Remove yarn commands in documentations
  src/Autocomplete/doc/index.rst
  src/Chartjs/doc/index.rst
  src/Cropperjs/doc/index.rst
  src/Dropzone/doc/index.rst
  src/LazyImage/doc/index.rst
  src/LiveComponent/doc/index.rst
  src/Notify/doc/index.rst
  src/React/doc/index.rst
  src/Svelte/doc/index.rst
  src/Swup/doc/index.rst
  src/TogglePassword/doc/index.rst
  src/Translator/doc/index.rst
  src/Turbo/CONTRIBUTING.md
  src/Turbo/README.md
  src/Turbo/doc/index.rst
  src/Typed/doc/index.rst
  src/Vue/doc/index.rst
Labels: Status: Needs Review

#2265 [Autocomplete] Add missing types
  src/Autocomplete/src/AutocompleteBundle.php
  src/Autocomplete/src/AutocompleterRegistry.php
  src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php
  src/Autocomplete/src/DependencyInjection/AutocompleteFormTypePass.php
  src/Autocomplete/src/Maker/MakeAutocompleteField.php
Labels: Status: Needs Review

#2267 [Autocomplete] Remove symfony/string dependency
  src/Autocomplete/composer.json
  src/Autocomplete/src/Form/AsEntityAutocompleteField.php
  src/Autocomplete/tests/Unit/Form/AsEntityAutocompleteFieldTest.php
Labels: Status: Reviewed, Autocomplete

#2268 [Site] Isolate React/Svelte build
  ux.symfony.com/assets/build/README.md
  ux.symfony.com/assets/react/app-react.js
  ux.symfony.com/assets/react/components/PackageList.jsx
  ux.symfony.com/assets/react/dist/components/PackageList.js
  ux.symfony.com/assets/react/dist/controllers/PackageSearch.js
  ux.symfony.com/assets/react/src/components/PackageList.jsx
  ux.symfony.com/assets/react/src/controllers/PackageSearch.jsx
  ux.symfony.com/assets/react/src/package.json
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_PackageList.scss
  ux.symfony.com/assets/svelte/app-svelte.js
  ux.symfony.com/assets/svelte/dist/components/PackageList.js
  ux.symfony.com/assets/svelte/dist/controllers/PackageSearch.js
  ux.symfony.com/assets/svelte/src/build.js
  ux.symfony.com/assets/svelte/src/components/PackageList.svelte
  ux.symfony.com/assets/svelte/src/controllers/PackageSearch.svelte
  ux.symfony.com/assets/svelte/src/package.json
  ux.symfony.com/assets/vue/app-vue.js
  ux.symfony.com/assets/vue/components/PackageList.js
  ux.symfony.com/assets/vue/controllers/PackageSearch.js
  ux.symfony.com/config/packages/asset_mapper.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/templates/components/FileTree.html.twig
  ux.symfony.com/templates/components/Package/PackageListItem.html.twig
  ux.symfony.com/templates/components/Package/SearchPackages.html.twig
  ux.symfony.com/templates/main/_file_tree.html.twig
  ux.symfony.com/templates/main/_package_in_list.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
  ux.symfony.com/templates/ux_packages/live_component.html.twig
  ux.symfony.com/templates/ux_packages/react.html.twig
  ux.symfony.com/templates/ux_packages/svelte.html.twig
  ux.symfony.com/templates/ux_packages/swup.html.twig
  ux.symfony.com/templates/ux_packages/vue.html.twig
  ux.symfony.com/yarn.lock
Labels: Status: Needs Review, Site

#2264 [Autocomplete] Remove unused "symfony/security-csrf" dev dependency
  src/Autocomplete/composer.json
Labels: Status: Reviewed, Autocomplete

#2274 Update index.rst
  src/LiveComponent/doc/index.rst
Labels: docs, Status: Needs Review

#2270 Remove stimulus-bundle unnecessary warning on documentation
  src/Chartjs/doc/index.rst
  src/LiveComponent/doc/index.rst
  src/Map/doc/index.rst
  src/React/doc/index.rst
  src/Svelte/doc/index.rst
  src/Turbo/doc/index.rst
  src/Vue/doc/index.rst
Labels: Status: Needs Review

#2275 Fix a typo in UX Icons docs
  src/Icons/doc/index.rst
Labels: Bug, Status: Needs Review

#2289 [Icons] Patch to handle Iconify API change
  src/Icons/src/Iconify.php
  src/Icons/tests/Unit/IconifyTest.php
Labels: Bug, Status: Reviewed, Icons

#2287 [Icons] Improve `icons:lock` command verbosity
  src/Icons/src/Command/LockIconsCommand.php
  src/Icons/src/Iconify.php
Labels: Status: Reviewed, Icons

#2285 [Autocomplete] Update AutocompleteBundle.de.php
  src/Autocomplete/translations/AutocompleteBundle.de.php
Labels: Status: Reviewed, Autocomplete

#2279 [Autocomplete] Translate "Add ..." text with remote data setup
  src/Autocomplete/CHANGELOG.md
  src/Autocomplete/assets/dist/controller.js
  src/Autocomplete/assets/src/controller.ts
  src/Autocomplete/translations/AutocompleteBundle.nl.php
Labels: Bug, Status: Reviewed

#2283 [React] Add `permanent` option to `react_component` function
  src/React/CHANGELOG.md
  src/React/assets/dist/render_controller.d.ts
  src/React/assets/dist/render_controller.js
  src/React/assets/src/render_controller.ts
  src/React/doc/index.rst
  src/React/src/Twig/ReactComponentExtension.php
  src/React/tests/Twig/ReactComponentExtensionTest.php
Labels: Bug, Status: Needs Review, Feature, React

#2286 [React] Update phpunit.xml.dist
  src/React/phpunit.xml.dist
Labels: Status: Needs Review, React

#2293 [Site] Update dependencies
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
Labels: Status: Needs Review, Site

#2294 Update AutocompleteBundle.tr.php
  src/Autocomplete/translations/AutocompleteBundle.tr.php
Labels: Status: Reviewed

#2251 [LiveComponent] Remove CSRF tokens - rely on same-origin/CORS instead
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/assets/dist/Backend/Backend.d.ts
  src/LiveComponent/assets/dist/Backend/RequestBuilder.d.ts
  src/LiveComponent/assets/dist/live_controller.d.ts
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Backend/Backend.ts
  src/LiveComponent/assets/src/Backend/RequestBuilder.ts
  src/LiveComponent/assets/src/Component/index.ts
  src/LiveComponent/assets/src/live_controller.ts
  src/LiveComponent/assets/test/Backend/RequestBuilder.test.ts
  src/LiveComponent/assets/test/controller/render.test.ts
  src/LiveComponent/assets/test/tools.ts
  src/LiveComponent/composer.json
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/Attribute/AsLiveComponent.php
  src/LiveComponent/src/DependencyInjection/Compiler/OptionalDependencyPass.php
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/EventListener/LiveComponentSubscriber.php
  src/LiveComponent/src/Test/TestLiveComponent.php
  src/LiveComponent/src/Util/ChildComponentPartialRenderer.php
  src/LiveComponent/src/Util/LiveAttributesCollection.php
  src/LiveComponent/src/Util/LiveControllerAttributesCreator.php
  src/LiveComponent/tests/Fixtures/Component/ComponentWithEmit.php
  src/LiveComponent/tests/Fixtures/Component/DisabledCsrf.php
  src/LiveComponent/tests/Fixtures/Component/FormWithCollectionTypeComponent.php
  src/LiveComponent/tests/Fixtures/Component/ValidatingComponent.php
  src/LiveComponent/tests/Fixtures/Form/BlogPostFormLiveCollectionType.php
  src/LiveComponent/tests/Fixtures/Form/BlogPostFormType.php
  src/LiveComponent/tests/Fixtures/Form/CommentFormType.php
  src/LiveComponent/tests/Fixtures/Form/FormWithManyDifferentFieldsType.php
  src/LiveComponent/tests/Fixtures/Kernel.php
  src/LiveComponent/tests/Fixtures/templates/csrf.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_form_with_collection_type.html.twig
  src/LiveComponent/tests/Functional/Controller/BatchActionControllerTest.php
  src/LiveComponent/tests/Functional/EventListener/AddLiveAttributesSubscriberTest.php
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/Form/ComponentWithFormTest.php
  src/LiveComponent/tests/Integration/EventListener/DataModelPropsSubscriberTest.php
  src/LiveComponent/tests/Unit/Util/LiveAttributesCollectionTest.php
Labels: Status: Reviewed, LiveComponent

#2297 [Autocomplete] Adjust index.rst format
  src/Autocomplete/doc/index.rst
Labels: docs, Status: Reviewed, Autocomplete

#2295 [AutoComplete] Note form requirements
  src/Autocomplete/doc/index.rst
Labels: docs, Status: Reviewed, Autocomplete

#2299 Update jetbrains stimulus plugin url.
  src/StimulusBundle/doc/index.rst
Labels: Status: Reviewed

#2308 Add myself to code-owners
  .github/CODEOWNERS
Labels: Status: Needs Review

#2304 [StimulusBundle] Check controllers source files for laziness
  src/StimulusBundle/src/AssetMapper/ControllersMapGenerator.php
  src/StimulusBundle/tests/AssetMapper/ControllersMapGeneratorTest.php
  src/StimulusBundle/tests/AssetMapper/StimulusControllerLoaderFunctionalTest.php
  src/StimulusBundle/tests/fixtures/assets/more-controllers/minified-controller.js
Labels: Bug, Status: Reviewed, StimulusBundle

#2302 [Turbo] Add generic `<Turbo:Stream>` component
  src/Turbo/CHANGELOG.md
  src/Turbo/templates/components/Stream.html.twig
Labels: Status: Reviewed, Feature, Turbo

#2303 [Turbo] Add `<Turbo:Frame>` component
  src/Turbo/CHANGELOG.md
  src/Turbo/doc/index.rst
  src/Turbo/templates/components/Frame.html.twig
Labels: Status: Reviewed, Feature, Turbo

#2310 [Site] Update `bin/link-locally`
  ux.symfony.com/bin/link-locally
Labels: Status: Reviewed, Site

#2314 [Icons] Fix commands receive polluted SVG
  src/Icons/src/Command/ImportIconCommand.php
  src/Icons/src/Command/LockIconsCommand.php
  src/Icons/src/Iconify.php
  src/Icons/tests/Unit/IconifyTest.php
Labels: Bug, Status: Reviewed, Icons

#2313 [LiveComponent] Fix documentation for select data-model
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed, LiveComponent
