Repository symfony/ux, pull requests merged in 2024-01, with the labels that each got.

#1381 [Site] Load importmap polyfill conditionnaly
  ux.symfony.com/config/packages/asset_mapper.yaml
  ux.symfony.com/templates/base.html.twig
Labels: Status: Waiting Feedback, Feature

#1428 [LiveComponent] Update importmap conf in package.json
  src/LiveComponent/assets/package.json
Labels: Status: Needs Review

#1392 [LiveComponent] Fix loadingDirectives match elements from nested components
  src/LiveComponent/assets/dist/Component/plugins/LoadingPlugin.d.ts
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Component/plugins/LoadingPlugin.ts
  src/LiveComponent/assets/test/controller/loading.test.ts
  yarn.lock
Labels: Bug, Status: Needs Review

#1429 Prepping changelogs for 2.14.0
  src/Autocomplete/CHANGELOG.md
  src/Chartjs/CHANGELOG.md
  src/LiveComponent/CHANGELOG.md
  src/StimulusBundle/CHANGELOG.md
  src/TwigComponent/CHANGELOG.md
Labels: Status: Needs Review
