Repository symfony/ux, pull requests merged in 2024-04, with the labels that each got.

#1663 [Doc] UX Icons doc tweaks
  src/Icons/doc/index.rst
Labels: documentation, Status: Needs Review

#1672 [Website] Fix some links in the UX Icons page
  ux.symfony.com/templates/icons/_aside.html.twig
Labels: Status: Reviewed

#1678 chore: typo
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#1696 [Site] Solidarity banner
  ux.symfony.com/assets/images/clock.png
  ux.symfony.com/assets/images/clock.webp
  ux.symfony.com/assets/images/icons/heart.svg
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/templates/_banner.html.twig
  ux.symfony.com/templates/base.html.twig
Labels: Status: Needs Review

#1673 [Site] Add "Icons" menu item
  ux.symfony.com/assets/styles/sections/_nav.scss
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/_nav.html.twig
  ux.symfony.com/tests/Functional/IconsTest.php
Labels: Status: Reviewed

#1703 Updated parameter order to match order in the constructor
  src/LiveComponent/doc/index.rst
Labels: documentation, Status: Needs Review

#1692 [Doc] Fix Icons doc
  src/Icons/doc/index.rst
Labels: Status: Needs Review

#1688 [Icons] Fix Icon missing width/height
  src/Icons/src/Iconify.php
Labels: Bug, Status: Needs Review

#1658 [Icons] Add Search Command
  src/Icons/config/iconify.php
  src/Icons/doc/index.rst
  src/Icons/src/Command/SearchIconCommand.php
  src/Icons/src/Iconify.php
  src/Icons/tests/Integration/Command/SearchIconCommandTest.php
Labels: Status: Reviewed, Feature

#1706 [Site] Fix banner
  ux.symfony.com/assets/images/clock.png
  ux.symfony.com/assets/images/clock.webp
  ux.symfony.com/assets/images/heart.png
  ux.symfony.com/assets/images/heart.webp
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/templates/_banner.html.twig
Labels: Status: Reviewed

#1707 [Site] Add og:image
  ux.symfony.com/assets/images/symfony-ux.png
  ux.symfony.com/assets/images/symfony-ux.svg
  ux.symfony.com/assets/images/symfony-ux.webp
  ux.symfony.com/templates/base.html.twig
Labels: Status: Needs Review

#1653 [Twig] CVA - Rework implementation + documentation
  src/TwigComponent/src/CVA.php
  src/TwigComponent/src/Twig/ComponentExtension.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1699 [Autocomplete] Command make:autocomplete-field output a doc compliant class
  src/Autocomplete/src/Maker/MakeAutocompleteField.php
  src/Autocomplete/src/Maker/skeletons/AutocompleteField.tpl.php
Labels: Status: Reviewed

#1705 [TwigComponent] Fix configuration namespace end with "\"
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed

#1710 [Twig] Resolving boolean as variant keys
  src/TwigComponent/src/CVA.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1690 [Icons] Set aria-hidden="true" when title/label not set
  src/Icons/src/IconRenderer.php
  src/Icons/tests/Fixtures/templates/template1.html.twig
  src/Icons/tests/Integration/RenderIconsInTwigTest.php
  src/Icons/tests/Unit/IconRendererTest.php
Labels: Status: Reviewed

#1709 [Twig] Handle aria-* attribute boolean values
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed

#1716 [Site] fix: hide IconSearchBox on mobile when AppHeader is open
  ux.symfony.com/assets/styles/components/_IconSearch.scss
Labels: Status: Reviewed

#1679 [Demo] Infinite scroll 1/2
  ux.symfony.com/assets/controllers/browser-controller.js
  ux.symfony.com/assets/icons/symfony.svg
  ux.symfony.com/assets/images/icons/circle-help.svg
  ux.symfony.com/assets/images/icons/lock.svg
  ux.symfony.com/assets/images/icons/refresh.svg
  ux.symfony.com/assets/images/live_demo/infinite-scroll.png
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/app/_html.scss
  ux.symfony.com/assets/styles/components/_Browser.scss
  ux.symfony.com/assets/styles/components/_ProductGrid.scss
  ux.symfony.com/src/Controller/Demo/LiveComponentDemoController.php
  ux.symfony.com/src/Service/EmojiCollection.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/src/Twig/ProductGrid.php
  ux.symfony.com/templates/components/Browser.html.twig
  ux.symfony.com/templates/components/ProductGrid.html.twig
  ux.symfony.com/templates/demos/live_component/infinite_scroll.html.twig
  ux.symfony.com/templates/liveDemoBase.html.twig
Labels: Status: Needs Review

#1723 [Autocomplete] Use `choice_value` in the `WrappedEntityTypeAutocompleter` in `EntityAutocompleteField`
  src/Autocomplete/CHANGELOG.md
  src/Autocomplete/src/Form/WrappedEntityTypeAutocompleter.php
  src/Autocomplete/tests/Fixtures/Entity/Category.php
  src/Autocomplete/tests/Fixtures/Factory/CategoryFactory.php
  src/Autocomplete/tests/Fixtures/Form/CategoryWithCallbackAsCustomValue.php
  src/Autocomplete/tests/Fixtures/Form/CategoryWithPropertyNameAsCustomValue.php
  src/Autocomplete/tests/Fixtures/Kernel.php
  src/Autocomplete/tests/Functional/FieldAutocompleterTest.php
Labels: Status: Reviewed

#1466 [Site] Add changelog page
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_Changelog.scss
  ux.symfony.com/assets/styles/utilities/_rich-text.scss
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/src/Controller/ChangelogController.php
  ux.symfony.com/src/Service/Changelog/ChangelogProvider.php
  ux.symfony.com/src/Twig/Components/ChangelogItem.php
  ux.symfony.com/templates/_footer.html.twig
  ux.symfony.com/templates/changelog.html.twig
  ux.symfony.com/templates/components/ChangelogItem.html.twig
  ux.symfony.com/tests/Twig/Components/ChangelogItemTest.php
Labels: Status: Reviewed

#1724 [Icons] Fix Icon aliases not found
  src/Icons/src/Iconify.php
  src/Icons/tests/Integration/RenderIconsInTwigTest.php
  src/Icons/tests/Unit/IconifyTest.php
Labels: Status: Reviewed

#1726 [Site] Add tags
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_DemoCard.scss
  ux.symfony.com/assets/styles/components/_Tag.scss
  ux.symfony.com/src/Model/LiveDemo.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/templates/components/DemoCard.html.twig
Labels: Status: Reviewed

#1725 [Site] Fix infinite demo CS
  ux.symfony.com/src/Service/EmojiCollection.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/src/Twig/ProductGrid.php
Labels: Status: Reviewed

#1729 [Site] Fix InfiniteScroll demo
  ux.symfony.com/assets/styles/components/_Browser.scss
  ux.symfony.com/assets/styles/components/_ProductGrid.scss
  ux.symfony.com/templates/components/PrevNextDemo.html.twig
  ux.symfony.com/templates/demos/live_component/infinite_scroll.html.twig
Labels: Status: Needs Review

#1731 [Icons] Remove lost configuration code
  src/Icons/doc/index.rst
Labels: Status: Needs Review

#1728 [Site] Lighten bootstrap
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/templates/components/FoodVote.html.twig
Labels: Status: Needs Review

#1727 [Site] Fix LiveMemory components
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/assets/styles/demos/live-memory.min.css
Labels: Status: Reviewed

#1734 [Twig] add additional CVA boolean tests
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed

#1735 [Site] cs fixes
  ux.symfony.com/src/Service/EmojiCollection.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/tests/Twig/Components/ChangelogItemTest.php
Labels: Status: Needs Review

#1396 [LiveComponent] Alias URL bound props
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/assets/test/controller/query-binding.test.ts
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/Attribute/LiveProp.php
  src/LiveComponent/src/Metadata/LiveComponentMetadata.php
  src/LiveComponent/src/Metadata/LivePropMetadata.php
  src/LiveComponent/src/Metadata/UrlMapping.php
  src/LiveComponent/src/Util/LiveControllerAttributesCreator.php
  src/LiveComponent/src/Util/QueryStringPropsExtractor.php
  src/LiveComponent/tests/Fixtures/Component/ComponentWithUrlBoundProps.php
  src/LiveComponent/tests/Fixtures/templates/components/component_with_url_bound_props.html.twig
  src/LiveComponent/tests/Fixtures/templates/render_component_with_url_bound_props.html.twig
  src/LiveComponent/tests/Functional/EventListener/AddLiveAttributesSubscriberTest.php
  src/LiveComponent/tests/Functional/EventListener/QueryStringInitializerSubscriberTest.php
  src/LiveComponent/tests/Functional/Metadata/LiveComponentMetadataFactoryTest.php
  src/LiveComponent/tests/Functional/Util/QueryStringPropsExtractorTest.php
Labels: Status: Needs Review, Status: Waiting Feedback, Feature

#1740 [Site] upgrade to PHP 8.3
  .github/workflows/ux.symfony.com.yaml
  ux.symfony.com/.platform.app.yaml
  ux.symfony.com/bin/console
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/packages/doctrine.yaml
  ux.symfony.com/config/packages/monolog.yaml
  ux.symfony.com/config/packages/translation.yaml
  ux.symfony.com/symfony.lock
  ux.symfony.com/tests/bootstrap.php
Labels: Status: Reviewed

#1750 [Site] Fix TerminalCommand copy
  ux.symfony.com/templates/components/TerminalCommand.html.twig
Labels: Status: Reviewed

#1746 [Site] Update RegistrationForm.html.twig use form_end instead of html form
  ux.symfony.com/templates/components/RegistrationForm.html.twig
Labels: Status: Reviewed

#1745 Allow debuging components with union typed props
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/tests/Fixtures/Component/UnionTypeProps.php
  src/TwigComponent/tests/Integration/Command/TwigComponentDebugCommandTest.php
Labels: Status: Reviewed

#1652 [TwigComponent] merge props from template with class props
  src/TwigComponent/src/ComponentRenderer.php
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/tests/Fixtures/Component/Conflict.php
  src/TwigComponent/tests/Fixtures/Component/FlashMessage.php
  src/TwigComponent/tests/Fixtures/templates/component_with_conflict_between_props_from_template_and_class.html.twig
  src/TwigComponent/tests/Fixtures/templates/component_with_props_from_template_and_class.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/Conflict.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/FlashMessage.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Status: Reviewed

#1743 [Site] improvements/fixes
  ux.symfony.com/assets/controllers/code-highlighter-controller.js
  ux.symfony.com/config/services.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Service/CommonMark/CodeExtension.php
  ux.symfony.com/src/Service/CommonMark/CodeRenderer.php
  ux.symfony.com/templates/ux_packages/translator.html.twig
Labels: Status: Needs Review

#1741 [Site] update to Symfony 7.0
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/packages/framework.yaml
  ux.symfony.com/config/packages/routing.yaml
  ux.symfony.com/config/packages/uid.yaml
  ux.symfony.com/config/packages/validator.yaml
  ux.symfony.com/symfony.lock
Labels: Status: Reviewed

#1045 [Turbo] Use blocks instead of partials to render turbo-streams
  src/Turbo/doc/index.rst
Labels: Status: Reviewed

#1752 [Site] update Route attribute namespace
  ux.symfony.com/src/Controller/Demo/LiveComponentDemoController.php
  ux.symfony.com/src/Controller/DemosController.php
  ux.symfony.com/src/Controller/MainController.php
  ux.symfony.com/src/Controller/UxPackage/AutocompleteController.php
  ux.symfony.com/src/Controller/UxPackage/ChartjsController.php
  ux.symfony.com/src/Controller/UxPackage/CropperjsController.php
  ux.symfony.com/src/Controller/UxPackage/DropzoneController.php
  ux.symfony.com/src/Controller/UxPackage/LazyImageController.php
  ux.symfony.com/src/Controller/UxPackage/LiveComponentController.php
  ux.symfony.com/src/Controller/UxPackage/NotifyController.php
  ux.symfony.com/src/Controller/UxPackage/ReactController.php
  ux.symfony.com/src/Controller/UxPackage/SvelteController.php
  ux.symfony.com/src/Controller/UxPackage/SwupController.php
  ux.symfony.com/src/Controller/UxPackage/TogglePasswordController.php
  ux.symfony.com/src/Controller/UxPackage/TranslatorController.php
  ux.symfony.com/src/Controller/UxPackage/TurboController.php
  ux.symfony.com/src/Controller/UxPackage/TwigComponentController.php
  ux.symfony.com/src/Controller/UxPackage/TypedController.php
  ux.symfony.com/src/Controller/UxPackage/VueController.php
  ux.symfony.com/src/Controller/UxPackagesController.php
Labels: Status: Needs Review

#1751 Auto-close PRs on subtree-splits
  .github/sync-packages.php
  .github/workflows/package-tests.yml
  src/Autocomplete/.gitattributes
  src/Autocomplete/.github/PULL_REQUEST_TEMPLATE.md
  src/Autocomplete/.github/workflows/check-subtree-split.yml
  src/Chartjs/.gitattributes
  src/Chartjs/.github/PULL_REQUEST_TEMPLATE.md
  src/Chartjs/.github/workflows/check-subtree-split.yml
  src/Cropperjs/.gitattributes
  src/Cropperjs/.github/PULL_REQUEST_TEMPLATE.md
  src/Cropperjs/.github/workflows/check-subtree-split.yml
  src/Dropzone/.gitattributes
  src/Dropzone/.github/PULL_REQUEST_TEMPLATE.md
  src/Dropzone/.github/workflows/check-subtree-split.yml
  src/Icons/.gitattributes
  src/Icons/.github/PULL_REQUEST_TEMPLATE.md
  src/Icons/.github/workflows/check-subtree-split.yml
  src/LazyImage/.gitattributes
  src/LazyImage/.github/PULL_REQUEST_TEMPLATE.md
  src/LazyImage/.github/workflows/check-subtree-split.yml
  src/LiveComponent/.gitattributes
  src/LiveComponent/.github/PULL_REQUEST_TEMPLATE.md
  src/LiveComponent/.github/workflows/check-subtree-split.yml
  src/Notify/.gitattributes
  src/Notify/.github/PULL_REQUEST_TEMPLATE.md
  src/Notify/.github/workflows/check-subtree-split.yml
  src/React/.gitattributes
  src/React/.github/PULL_REQUEST_TEMPLATE.md
  src/React/.github/workflows/check-subtree-split.yml
  src/StimulusBundle/.gitattributes
  src/StimulusBundle/.github/PULL_REQUEST_TEMPLATE.md
  src/StimulusBundle/.github/workflows/check-subtree-split.yml
  src/Svelte/.gitattributes
  src/Svelte/.github/PULL_REQUEST_TEMPLATE.md
  src/Svelte/.github/workflows/check-subtree-split.yml
  src/Swup/.gitattributes
  src/Swup/.github/PULL_REQUEST_TEMPLATE.md
  src/Swup/.github/workflows/check-subtree-split.yml
  src/TogglePassword/.gitattributes
  src/TogglePassword/.github/PULL_REQUEST_TEMPLATE.md
  src/TogglePassword/.github/workflows/check-subtree-split.yml
  src/Translator/.gitattributes
  src/Translator/.github/PULL_REQUEST_TEMPLATE.md
  src/Translator/.github/workflows/check-subtree-split.yml
  src/Turbo/.gitattributes
  src/Turbo/.github/PULL_REQUEST_TEMPLATE.md
  src/Turbo/.github/workflows/check-subtree-split.yml
  src/TwigComponent/.gitattributes
  src/TwigComponent/.github/PULL_REQUEST_TEMPLATE.md
  src/TwigComponent/.github/workflows/check-subtree-split.yml
  src/Typed/.gitattributes
  src/Typed/.github/PULL_REQUEST_TEMPLATE.md
  src/Typed/.github/workflows/check-subtree-split.yml
  src/Vue/.gitattributes
  src/Vue/.github/PULL_REQUEST_TEMPLATE.md
  src/Vue/.github/workflows/check-subtree-split.yml
Labels: Status: Reviewed

#1753 [Stimulus] Allow Twig 3.9
  src/StimulusBundle/composer.json
Labels: Status: Needs Review

#1755 [LazyImage] Cache BlurHash, close #2
  src/LazyImage/composer.json
  src/LazyImage/doc/index.rst
  src/LazyImage/src/BlurHash/BlurHash.php
  src/LazyImage/src/BlurHash/CachedBlurHash.php
  src/LazyImage/src/DependencyInjection/Configuration.php
  src/LazyImage/src/DependencyInjection/LazyImageExtension.php
  src/LazyImage/tests/BlurHash/BlurHashTest.php
Labels: Status: Reviewed

#1487 [TwigComponent] Twig "use_yield" compatibility
  src/TwigComponent/composer.json
  src/TwigComponent/src/Twig/ComponentNode.php
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/tests/Fixtures/templates/non_embedded_component_blocks_with_fallback.html.twig
  src/TwigComponent/tests/Fixtures/templates/tags/embedded_component.html.twig
  src/TwigComponent/tests/Integration/ComponentLexerTest.php
  src/TwigComponent/tests/Integration/EmbeddedComponentTest.php
Labels: Status: Reviewed

#1757 [LiveComponent][TwigComponent] Allow Twig 3.9
  src/LiveComponent/composer.json
  src/TwigComponent/src/Twig/ComponentNode.php
Labels: Status: Reviewed

#1756 [Site] Fix input range colors
  ux.symfony.com/assets/styles/_variables.scss
  ux.symfony.com/assets/styles/vendor/_bootstrap.scss
Labels: Status: Reviewed

#1761 [LazyImage] Fix cache implementation
  src/LazyImage/src/BlurHash/BlurHash.php
  src/LazyImage/src/BlurHash/CachedBlurHash.php
  src/LazyImage/src/DependencyInjection/LazyImageExtension.php
  src/LazyImage/tests/BlurHash/BlurHashTest.php
Labels: Status: Reviewed

#1760 [Turbo] fix sca
  src/Turbo/phpstan.neon.dist
  src/Turbo/src/Doctrine/BroadcastListener.php
  src/Turbo/src/Doctrine/ClassUtil.php
Labels: Status: Needs Review

#1763 remove duplicate key
  src/StimulusBundle/tests/Twig/StimulusTwigExtensionTest.php
Labels: Status: Reviewed

#1769 Update ProductGrid.html.twig
  ux.symfony.com/templates/components/ProductGrid.html.twig
Labels: Status: Reviewed

#1759 [LiveComponent] hide property-info deprecations in Symfony 7.1
  src/LiveComponent/composer.json
  src/LiveComponent/phpunit.xml.dist
  src/LiveComponent/tests/baseline-ignore
Labels: Status: Needs Review

#1766 [LazyImage] refactor to `twig.runtime` & support `intervention/image` 3
  src/LazyImage/CHANGELOG.md
  src/LazyImage/composer.json
  src/LazyImage/src/BlurHash/BlurHash.php
  src/LazyImage/src/DependencyInjection/LazyImageExtension.php
  src/LazyImage/tests/BlurHash/BlurHashTest.php
Labels: Status: Needs Review

#1771 [LazyImage] Re-add forgotten twig.runtime
  src/LazyImage/src/DependencyInjection/LazyImageExtension.php
  src/LazyImage/src/Twig/BlurHashExtension.php
  src/LazyImage/src/Twig/BlurHashRuntime.php
Labels: Status: Reviewed

#1775 #1770 [Autocomplete] Ignore the ExtraLazyChoiceLoader if the parent $loader is null
  src/Autocomplete/src/Form/BaseEntityAutocompleteType.php
Labels: Status: Needs Review

#1777 [Autocomplete] fix cs
  src/Autocomplete/src/Form/BaseEntityAutocompleteType.php
Labels: Status: Needs Review

#1779 [LiveComponent] Add a note about render:finished event
  src/LiveComponent/doc/index.rst
Labels: documentation, Status: Needs Review, LiveComponent

#1694 [LiveComponent] set LiveArg value to null if empty string
  src/LiveComponent/src/Attribute/LiveArg.php
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/EventListener/LiveComponentSubscriber.php
  src/LiveComponent/src/Util/LiveRequestDataParser.php
  src/LiveComponent/src/ValueResolver/LiveArgValueResolver.php
  src/LiveComponent/src/ValueResolver/LiveArgValueResolverTrait.php
  src/LiveComponent/tests/Fixtures/Component/Component6.php
  src/LiveComponent/tests/Fixtures/templates/components/component6.html.twig
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/Test/InteractsWithLiveComponentsTest.php
Labels: Status: Reviewed

#1772 [TwigComponent] Fix LiveComponent namespace mapping
  src/TwigComponent/src/Twig/TemplateNameParser.php
  src/TwigComponent/tests/Unit/Twig/TemplateNameParserTest.php
Labels: Bug, Status: Needs Review, TwigComponent

#1781 [LazyImage] Abstract image content fetching
  src/LazyImage/doc/index.rst
  src/LazyImage/src/BlurHash/BlurHash.php
  src/LazyImage/src/DependencyInjection/Configuration.php
  src/LazyImage/src/DependencyInjection/LazyImageExtension.php
  src/LazyImage/tests/BlurHash/BlurHashTest.php
  src/LazyImage/tests/Fixtures/BlurHash/LoggedFetchImageContent.php
Labels: Status: Reviewed, Feature, LazyImage

#1784 [Site] Grouped fixes
  ux.symfony.com/.platform.app.yaml
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/assets/styles/components/_Changelog.scss
  ux.symfony.com/assets/styles/components/_Pagination.scss
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/bundles.php
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Controller/UxPackage/SwupController.php
  ux.symfony.com/symfony.lock
  ux.symfony.com/templates/components/Icon/IconModal.html.twig
  ux.symfony.com/templates/components/PrevNextDemo.html.twig
  ux.symfony.com/templates/icons/index.html.twig
  ux.symfony.com/templates/liveDemoBase.html.twig
  ux.symfony.com/templates/ux_packages/swup.html.twig
  ux.symfony.com/tests/Functional/LiveComponentDemosTest.php
  ux.symfony.com/tests/Functional/UxPackagesTest.php
Labels: Status: Needs Review, Site

#1789 [Doc] Misc fixes in Twig Component docs
  src/TwigComponent/doc/index.rst
Labels: documentation, Status: Reviewed

#1790 [Doc] Remove the --dir option in debug:twig-component command
  src/TwigComponent/doc/index.rst
Labels: Bug, documentation, Status: Needs Review

#1791 [Site] refactor commonmark config
  ux.symfony.com/config/services.yaml
  ux.symfony.com/src/Service/CommonMark/CodeExtension.php
  ux.symfony.com/src/Service/CommonMark/ConverterFactory.php
  ux.symfony.com/src/Twig/Components/ChangelogItem.php
  ux.symfony.com/tests/Twig/Components/ChangelogItemTest.php
Labels: Status: Reviewed, Site

#1792 [Icons] Fix warning when Iconset license URL is null
  src/Icons/src/Command/ImportIconCommand.php
  src/Icons/src/Command/LockIconsCommand.php
Labels: Status: Reviewed, Icons

#1794 [Site] adjust external link config
  ux.symfony.com/src/Service/CommonMark/ConverterFactory.php
Labels: Status: Needs Review, Site

#1783 [Site] Refactor Translator page
  ux.symfony.com/assets/controllers/translator-demo-block-controller.js
  ux.symfony.com/assets/controllers/translator-demo-controller.js
  ux.symfony.com/templates/ux_packages/translator.html.twig
  ux.symfony.com/templates/ux_packages/translator/_translator_demo_block.html.twig
Labels: Status: Reviewed, Site

#1798 [Icons] Use lowercase <twig:ux:icon /> in documentation
  src/Icons/README.md
  src/Icons/doc/index.rst
Labels: documentation, Status: Reviewed, Icons

#1805 [TwigComponent] Fix aria attribute cannot be removed
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed, TwigComponent

#1797 [Icons] Improve aria attributes rendering
  src/Icons/src/Icon.php
  src/Icons/src/IconRenderer.php
  src/Icons/tests/Integration/RenderIconsInTwigTest.php
  src/Icons/tests/Unit/IconRendererTest.php
  src/Icons/tests/Unit/IconTest.php
Labels: Status: Reviewed, Icons

#1780 [TwigComponent] Throws if exposed public prop is uninitialized
  src/TwigComponent/src/ComponentRenderer.php
Labels: Status: Reviewed, TwigComponent

#1801 [LiveComponent] Fix namespaces on documentation
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed, LiveComponent

#1808 [Site] switch from `highlight.js` to `tempest/highlight`
  ux.symfony.com/assets/controllers/code-highlighter-controller.js
  ux.symfony.com/assets/styles/vendor/_highlight.scss
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/services.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Service/CommonMark/CodeRenderer.php
  ux.symfony.com/src/Service/CommonMark/ConverterFactory.php
  ux.symfony.com/src/Twig/HighlightExtension.php
  ux.symfony.com/templates/components/CodeBlock.html.twig
  ux.symfony.com/templates/components/CodeLine.html.twig
  ux.symfony.com/templates/components/Icon/IconModal.html.twig
  ux.symfony.com/templates/ux_packages/translator.html.twig
  ux.symfony.com/templates/ux_packages/translator/_translator_demo_block.html.twig
Labels: Status: Reviewed, Site

#1810 [TwigComponent]: Fix silently failing tests
  src/TwigComponent/tests/Integration/ComponentFactoryTest.php
Labels: Status: Reviewed, TwigComponent

#1795 Adjust GHA to account for fabbot
  .github/workflows/test.yaml
Labels: Status: Reviewed

#1811 [Site] Adapt highlighted code blocks to tempest
  ux.symfony.com/assets/styles/components/_PackageHeader.scss
  ux.symfony.com/assets/styles/components/_Terminal.scss
  ux.symfony.com/assets/styles/vendor/_highlight.scss
  ux.symfony.com/templates/ux_packages/translator.html.twig
  ux.symfony.com/templates/ux_packages/translator/_translator_demo_block.html.twig
Labels: Status: Reviewed, Site
