Repository symfony/ux, pull requests merged in 2024-08, with the labels that each got.

#2027 [Doc] Fix some misc issues in UX Icons docs
  src/Icons/doc/index.rst
Labels: documentation, Status: Reviewed

#2023 [Icons] Add `ignore_not_found` config option
  src/Icons/CHANGELOG.md
  src/Icons/composer.json
  src/Icons/config/services.php
  src/Icons/doc/index.rst
  src/Icons/src/DependencyInjection/UXIconsExtension.php
  src/Icons/src/Twig/UXIconExtension.php
  src/Icons/src/Twig/UXIconRuntime.php
  src/Icons/tests/Unit/Twig/UXIconRuntimeTest.php
Labels: Status: Needs Review, Feature, Icons

#2031 [Map] Rename "symfony/ux-map-%s" to "symfony/ux-%s-map"
  src/Map/doc/index.rst
  src/Map/src/Bridge/Google/assets/package.json
  src/Map/src/Bridge/Google/composer.json
  src/Map/src/Bridge/Google/tests/GoogleRendererTest.php
  src/Map/src/Bridge/Leaflet/assets/package.json
  src/Map/src/Bridge/Leaflet/composer.json
  src/Map/src/Bridge/Leaflet/tests/LeafletRendererTest.php
  src/Map/src/Exception/UnsupportedSchemeException.php
  src/Map/src/Renderer/AbstractRenderer.php
  src/Map/src/UXMapBundle.php
  src/Map/tests/Renderer/NullRendererTest.php
  src/Map/tests/Renderer/RenderersTest.php
  src/Map/tests/TwigTest.php
  src/Map/tests/UXMapBundleTest.php
Labels: Bug, Status: Reviewed

#2032 [Map] Fix custom attribute "data-controller" usage
  src/Map/src/Bridge/Google/tests/GoogleRendererTest.php
  src/Map/src/Bridge/Leaflet/tests/LeafletRendererTest.php
  src/Map/src/Renderer/AbstractRenderer.php
Labels: Bug, Status: Needs Review

#2036 [Map][Leaflet] Fix Marker inside-circle
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
Labels: Bug, Status: Needs Review

#2035 [Map][Leaflet] Fix Popup's automatic-content
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
Labels: Bug, Status: Needs Review

#2037 [docs] Add missing end delimiter
  src/LiveComponent/doc/index.rst
Labels: Bug, documentation, Status: Reviewed

#2038 Update README.md
  README.md
Labels: Status: Reviewed

#2039 [Map] Change "BeforeConnect" for "BeforeCreate" in documentation
  src/Map/doc/index.rst
Labels: Status: Needs Review

#2040 [Map] Add "extra" data for markers and infowindows
  src/Map/assets/dist/abstract_map_controller.d.ts
  src/Map/assets/src/abstract_map_controller.ts
  src/Map/doc/index.rst
  src/Map/src/Bridge/Google/assets/dist/map_controller.js
  src/Map/src/Bridge/Google/assets/src/map_controller.ts
  src/Map/src/Bridge/Google/tests/GoogleRendererTest.php
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
  src/Map/src/Bridge/Leaflet/tests/LeafletRendererTest.php
  src/Map/src/InfoWindow.php
  src/Map/src/Marker.php
  src/Map/tests/InfoWindowTest.php
  src/Map/tests/MapTest.php
  src/Map/tests/MarkerTest.php
Labels: Status: Needs Review, Feature

#2043 [Doc] fix some comments in component defer part
  src/LiveComponent/doc/index.rst
Labels: documentation, Status: Needs Review

#2045 [Map] Add the possibility to not configure map zoom/center if fit bounds to markers
  src/Map/assets/dist/abstract_map_controller.d.ts
  src/Map/assets/src/abstract_map_controller.ts
  src/Map/doc/index.rst
  src/Map/src/Bridge/Google/assets/dist/map_controller.d.ts
  src/Map/src/Bridge/Google/assets/src/map_controller.ts
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.d.ts
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
  src/Map/src/Map.php
  src/Map/tests/MapTest.php
Labels: Status: Needs Review, Feature

#2044 [Map] Add support for `libraries` for Google Bridge, inject provider's SDK (`L` or `google`) to dispatched events
  src/Map/assets/dist/abstract_map_controller.d.ts
  src/Map/assets/dist/abstract_map_controller.js
  src/Map/assets/src/abstract_map_controller.ts
  src/Map/assets/test/abstract_map_controller.test.ts
  src/Map/src/Bridge/Google/README.md
  src/Map/src/Bridge/Google/assets/dist/map_controller.d.ts
  src/Map/src/Bridge/Google/assets/dist/map_controller.js
  src/Map/src/Bridge/Google/assets/src/map_controller.ts
  src/Map/src/Bridge/Google/assets/test/map_controller.test.ts
  src/Map/src/Bridge/Google/src/Renderer/GoogleRenderer.php
  src/Map/src/Bridge/Google/src/Renderer/GoogleRendererFactory.php
  src/Map/src/Bridge/Google/tests/GoogleRendererFactoryTest.php
  src/Map/src/Bridge/Leaflet/README.md
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.d.ts
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
Labels: Status: Needs Review, Feature

#2052 [Map] Re-add keyword "symfony-ux", to fix Symfony Flex `package.json` resolving
  src/Map/src/Bridge/Google/composer.json
  src/Map/src/Bridge/Leaflet/composer.json
Labels: Bug, Status: Reviewed

#2055 [Map][Leaflet] Fix marker icon gradients rendering, which can fails on some projects
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
Labels: Bug, Status: Reviewed

#2049 fix: warning and code formatting on Autocomplete
  src/Autocomplete/doc/index.rst
Labels: Status: Reviewed

#2046 Update naming of stimulus controller on default attributes - index.rst
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#2019 Adding convention to load Anonymous components from bundles
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/src/ComponentTemplateFinder.php
  src/TwigComponent/tests/Fixtures/Bundle/AcmeBundle/AcmeBundle.php
  src/TwigComponent/tests/Fixtures/Bundle/AcmeBundle/templates/components/Button.html.twig
  src/TwigComponent/tests/Fixtures/Kernel.php
  src/TwigComponent/tests/Integration/Command/TwigComponentDebugCommandTest.php
  src/TwigComponent/tests/Integration/ComponentFactoryTest.php
Labels: Status: Reviewed, Feature, TwigComponent

#2025 [Cookbook] - fix component_architecture
  ux.symfony.com/cookbook/component_architecture.md
Labels: Status: Reviewed

#2058 [Map] Fix doc link
  src/Map/doc/index.rst
Labels: Status: Needs Review

#2064 [Map] Fix Typo: Removal of an extra ";"
  src/Map/doc/index.rst
Labels: Status: Reviewed

#2062 doc: replace link "https://symfony.com/ux" by "https://ux.symfony.com/"
  src/Chartjs/README.md
  src/Chartjs/doc/index.rst
  src/Cropperjs/README.md
  src/Cropperjs/doc/index.rst
  src/Dropzone/README.md
  src/Dropzone/doc/index.rst
  src/LazyImage/README.md
  src/LazyImage/doc/index.rst
  src/Notify/README.md
  src/Notify/doc/index.rst
  src/React/doc/index.rst
  src/Svelte/doc/index.rst
  src/Swup/README.md
  src/Swup/doc/index.rst
  src/TogglePassword/README.md
  src/TogglePassword/doc/index.rst
  src/Translator/doc/index.rst
  src/Turbo/README.md
  src/Turbo/doc/index.rst
  src/Typed/README.md
  src/Typed/doc/index.rst
  src/Vue/doc/index.rst
Labels: Status: Reviewed

#2060 [Translator] Revert #1965, which break cache warmup for Symfony applications
  src/Translator/doc/index.rst
  src/Translator/src/DependencyInjection/TranslatorCompilerPass.php
  src/Translator/src/UxTranslatorBundle.php
  src/Translator/tests/Kernel/FrameworkAppKernel.php
  src/Translator/tests/UxTranslatorBundleTest.php
Labels: Bug, Status: Reviewed

#2063 [CI] Test ux.symfony.com with local UX packages
  .github/build-packages.php
  .github/workflows/ux.symfony.com.yaml
Labels: Status: Needs Review, DX

#2066 [Site] fix foundry deprecation
  ux.symfony.com/tests/Functional/LiveComponentDemosTest.php
Labels: Status: Needs Review, Site

#2065 [DX] mention documentation in README
  README.md
Labels: Status: Needs Review

#2053 [Site] UX Map page
  ux.symfony.com/.env
  ux.symfony.com/assets/controllers.json
  ux.symfony.com/assets/images/ux_packages/map-1200x675.png
  ux.symfony.com/assets/images/ux_packages/map.svg
  ux.symfony.com/assets/styles/components/_PackageBox.scss
  ux.symfony.com/assets/styles/components/_PackageHeader.scss
  ux.symfony.com/assets/styles/sections/_hero.scss
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/bundles.php
  ux.symfony.com/config/packages/ux_map.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Controller/UxPackage/MapController.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/src/Twig/Extension/PackageExtension.php
  ux.symfony.com/symfony.lock
  ux.symfony.com/templates/components/Hero.html.twig
  ux.symfony.com/templates/ux_packages/map.html.twig
  ux.symfony.com/templates/ux_packages/map/_aside.html.twig
  ux.symfony.com/templates/ux_packages/package.html.twig
  ux.symfony.com/tests/Functional/UxPackagesTest.php
Labels: Status: Reviewed, Site

#2067 [Site] Update file tree icons
  ux.symfony.com/assets/icons/file.svg
  ux.symfony.com/assets/styles/components/_FileTree.scss
  ux.symfony.com/templates/main/_file_tree.html.twig
Labels: Status: Reviewed, Site

#2069 [ux.symfony.com] Fix rendering/color issues on Map page
  ux.symfony.com/assets/styles/components/_PackageHeader.scss
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/templates/ux_packages/map.html.twig
Labels: Bug, Status: Reviewed

#2073 [Map] Rename `render_map` Twig function `ux_map`
  src/Map/CHANGELOG.md
  src/Map/doc/index.rst
  src/Map/src/Bridge/Google/README.md
  src/Map/src/Bridge/Leaflet/README.md
  src/Map/src/Twig/MapExtension.php
  src/Map/tests/TwigTest.php
Labels: Status: Reviewed

#2074 chore: run PHP-CS-Fixer
  src/Icons/src/Twig/UXIconRuntime.php
  src/LiveComponent/tests/Unit/Twig/LiveComponentRuntimeTest.php
Labels: Status: Needs Review

#2030 Fix: Original Throwable get lost during component render
  src/TwigComponent/src/Twig/ComponentExtension.php
Labels: Bug, Status: Needs Review

#2084 Configure ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/1-bug_report.md
  .github/ISSUE_TEMPLATE/2-feature_request.md
  .github/ISSUE_TEMPLATE/3-documentation.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Status: Reviewed, DX

#2075 [root] Upgrade JS build dependencies
  package.json
  rollup.config.js
  src/Autocomplete/assets/dist/controller.js
  src/Map/src/Bridge/Google/assets/dist/map_controller.d.ts
  src/React/assets/dist/register_controller.d.ts
  src/Svelte/assets/dist/register_controller.d.ts
  src/Vue/assets/dist/register_controller.d.ts
  yarn.lock
Labels: Status: Reviewed

#2080 [Map] Fix bridges .gitattributes
  src/Map/src/Bridge/Google/.gitattributes
  src/Map/src/Bridge/Leaflet/.gitattributes
Labels: Status: Reviewed

#2088 [TwigComponent] Fix debug command
  src/TwigComponent/doc/index.rst
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/tests/Fixtures/Bundle/AcmeBundle/templates/components/Table/Header.html.twig
  src/TwigComponent/tests/Integration/Command/TwigComponentDebugCommandTest.php
Labels: Bug, Status: Reviewed, TwigComponent

#2076 Fix Twig extension return types
  src/LazyImage/src/Twig/BlurHashExtension.php
  src/Map/src/Twig/MapExtension.php
  src/Notify/src/Twig/NotifyExtension.php
  src/Turbo/src/Twig/TwigExtension.php
Labels: Status: Needs Review

#2082 [TwigComponent][Doc] Twig code style & "boolean props" part
  src/TwigComponent/doc/index.rst
Labels: docs, Status: Reviewed, TwigComponent

#2092 [Site] Refresh banner
  ux.symfony.com/assets/styles/app/_root.scss
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/templates/_banner.html.twig
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
Labels: Status: Reviewed, Site

#2091 [Site] Support page
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/assets/styles/components/_SupportBox.scss
  ux.symfony.com/assets/styles/sections/_nav.scss
  ux.symfony.com/src/Controller/SitemapController.php
  ux.symfony.com/src/Controller/SupportController.php
  ux.symfony.com/templates/_footer.html.twig
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/support.html.twig
Labels: Status: Reviewed, Site

#2090 [Site] Documentation index
  ux.symfony.com/src/Controller/DocumentationController.php
  ux.symfony.com/templates/_footer.html.twig
  ux.symfony.com/templates/documentation/index.html.twig
Labels: docs, Status: Reviewed, Site

#2093 [GH] Link to UX support page
  .github/ISSUE_TEMPLATE/config.yml
Labels: Status: Reviewed

#2097 [Site] Minor fixes
  ux.symfony.com/assets/styles/vendor/_highlight.scss
  ux.symfony.com/src/Controller/SitemapController.php
  ux.symfony.com/templates/_aside.html.twig
  ux.symfony.com/templates/ux_packages/_package_links.html.twig
Labels: Status: Reviewed, Site

#2072 [Cookbook] English / doc / code corrections
  ux.symfony.com/cookbook/component_architecture.md
Labels: Status: Reviewed

#2079 [LiveComponent] Fix PHP8.4 errors + deprecations
  src/Icons/tests/Integration/Command/SearchIconCommandTest.php
  src/LiveComponent/composer.json
  src/LiveComponent/phpunit.xml.dist
  src/LiveComponent/tests/Fixtures/Dto/HoldsArrayOfDtos.php
  src/LiveComponent/tests/Fixtures/Entity/TodoItemFixtureEntity.php
  src/LiveComponent/tests/Fixtures/Factory/CompositeIdEntityFactory.php
  src/LiveComponent/tests/Fixtures/Factory/ForeignKeyIdEntityFactory.php
  src/LiveComponent/tests/Fixtures/Kernel.php
  src/LiveComponent/tests/Fixtures/Serializer/Entity2Normalizer.php
  src/LiveComponent/tests/Fixtures/Serializer/MoneyNormalizer.php
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/LiveResponderTest.php
  src/LiveComponent/tests/Functional/ValidatableComponentTraitTest.php
  src/LiveComponent/tests/Integration/EventListener/DataModelPropsSubscriberTest.php
  src/LiveComponent/tests/Integration/Hydration/DoctrineEntityHydrationExtensionTest.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
  src/LiveComponent/tests/Integration/Twig/LiveComponentExtensionTest.php
  src/LiveComponent/tests/Integration/Twig/LiveComponentRuntimeTest.php
  src/LiveComponent/tests/Integration/Util/FingerprintCalculatorTest.php
Labels: Status: Reviewed, Icons, LiveComponent

#2107 [Doc] Fix a Twig function name in UX Map docs
  src/Map/doc/index.rst
Labels: Bug, docs, Status: Reviewed

#2112 [UX Map] Misc updates in the docs
  src/Map/doc/index.rst
Labels: docs, Status: Reviewed, Map

#2113 [Map][Leaflet] Rename `leaflet` to `L` in event's payloads
  src/Map/src/Bridge/Leaflet/assets/dist/map_controller.js
  src/Map/src/Bridge/Leaflet/assets/src/map_controller.ts
Labels: Bug, Status: Reviewed, Map

#2114 [TwigComponent] Remove `$tag` parameter from `*Node`, as it is now deprecated by twig/twig 3.12
  src/TwigComponent/src/Twig/ComponentNode.php
  src/TwigComponent/src/Twig/ComponentTokenParser.php
  src/TwigComponent/src/Twig/PropsNode.php
Labels: Status: Needs Review, TwigComponent

#2094 [Autocomplete] Reset form state on each request for applications that reuse the Symfony application between requests
  src/Autocomplete/src/DependencyInjection/AutocompleteFormTypePass.php
  src/Autocomplete/src/Form/WrappedEntityTypeAutocompleter.php
Labels: Bug, Status: Reviewed, Autocomplete
