Repository symfony/ux, pull requests merged in 2024-02, with the labels that each got.

#1446 [Site] Fix Cloudflare wrongly minify CSS 4 / test 2
  ux.symfony.com/assets/styles/demos/_live-memory.scss
  ux.symfony.com/assets/styles/demos/live-memory.min.css
Labels: Status: Needs Review

#1434 fix: use method from metadata for live component test helper
  src/LiveComponent/src/Test/TestLiveComponent.php
Labels: Status: Needs Review

#1444 [StimulusBundle] Handles Windows directory separator when normalizing controller names
  src/StimulusBundle/src/AssetMapper/ControllersMapGenerator.php
Labels: Status: Needs Review

#1439 [CI] Upgrade actions/cache@v4
  .github/workflows/doctor-rst.yaml
  .github/workflows/test-turbo.yml
  .github/workflows/test.yaml
Labels: Status: Reviewed

#1441 [CI] Trim yarn JSON in run-vitest-all
  bin/run-vitest-all.sh
Labels: Status: Reviewed

#1448 Bumping changelog for 2.14.1
  src/LiveComponent/CHANGELOG.md
  src/StimulusBundle/CHANGELOG.md
  ux.symfony.com/src/Controller/Demo/LiveMemoryController.php
  ux.symfony.com/src/Twig/Components/LiveMemory/Board.php
Labels: Status: Needs Review

#1464 [Site] Using URL binding on live components demo
  ux.symfony.com/composer.lock
  ux.symfony.com/src/Twig/SearchPackages.php
Labels: Status: Needs Review

#1467 [StimulusBundle] UxPackageReader class doesn't support projects with varied structures using Composer with custom directory structure
  src/StimulusBundle/src/Ux/UxPackageReader.php
Labels: Status: Needs Review

#1453 CS Update
  src/Autocomplete/src/Doctrine/EntitySearchUtil.php
  src/Autocomplete/src/Form/ChoiceList/Loader/ExtraLazyChoiceLoader.php
  src/Autocomplete/tests/Integration/Doctrine/EntitySearchUtilTest.php
  src/LazyImage/src/BlurHash/BlurHash.php
  src/LiveComponent/src/Attribute/AsLiveComponent.php
  src/LiveComponent/src/Attribute/LiveProp.php
  src/LiveComponent/src/ComponentToolsTrait.php
  src/LiveComponent/src/LiveResponder.php
  src/LiveComponent/src/Metadata/LivePropMetadata.php
  src/LiveComponent/src/Test/InteractsWithLiveComponents.php
  src/LiveComponent/src/Test/TestLiveComponent.php
  src/LiveComponent/src/Twig/DeterministicTwigIdCalculator.php
  src/LiveComponent/src/Twig/TemplateCacheWarmer.php
  src/LiveComponent/src/Util/LiveControllerAttributesCreator.php
  src/LiveComponent/tests/Functional/Form/ComponentWithFormTest.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
  src/StimulusBundle/src/Dto/StimulusAttributes.php
  src/StimulusBundle/src/Twig/StimulusTwigExtension.php
  src/Translator/src/CacheWarmer/TranslationsCacheWarmer.php
  src/Turbo/src/Broadcaster/BroadcasterInterface.php
  src/Turbo/src/Broadcaster/IdAccessor.php
  src/Turbo/src/Broadcaster/TwigBroadcaster.php
  src/Turbo/src/Doctrine/BroadcastListener.php
  src/Turbo/src/Twig/TwigExtension.php
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/src/DataCollector/TwigComponentDataCollector.php
  src/TwigComponent/src/Event/PreRenderEvent.php
  src/TwigComponent/src/Test/InteractsWithTwigComponents.php
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/src/Twig/TwigPreLexer.php
  ux.symfony.com/src/Controller/Demo/LiveComponentDemoController.php
  ux.symfony.com/src/Controller/UxPackage/LiveComponentController.php
  ux.symfony.com/src/Controller/UxPackage/TurboController.php
  ux.symfony.com/src/LiveMemory/GameEngine.php
  ux.symfony.com/src/Model/RecipeFileTree.php
  ux.symfony.com/src/Serializer/UxPackageNormalizer.php
  ux.symfony.com/src/Service/UxPackageRepository.php
Labels: Status: Needs Review

#1471 [Turbo] Fixing support for not using old ClassUtils
  src/Turbo/src/Bridge/Mercure/Broadcaster.php
  src/Turbo/src/Broadcaster/TwigBroadcaster.php
  src/Turbo/src/Doctrine/BroadcastListener.php
  src/Turbo/src/Doctrine/ClassUtil.php
Labels: Status: Needs Review

#1473 Bumping 2.14.2 CHANGELOG and reverting minor feature temporarily
  src/StimulusBundle/CHANGELOG.md
  src/Turbo/CHANGELOG.md
  src/Turbo/assets/package.json
Labels: Status: Needs Review

#1475 [Turbo] add missing use statement
  src/Turbo/src/Doctrine/ClassUtil.php
Labels: Status: Reviewed

#1442 [Twig] Add (alternate) attribute rendering system
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
  src/TwigComponent/src/ComponentAttributes.php
  src/TwigComponent/tests/Fixtures/templates/components/RenderAttributes.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Reviewed

#1322 [Autocomplete] Allow passing extra options to the autocomplete fields
  src/Autocomplete/CHANGELOG.md
  src/Autocomplete/src/Checksum/ChecksumCalculator.php
  src/Autocomplete/src/Controller/EntityAutocompleteController.php
  src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php
  src/Autocomplete/src/Form/AutocompleteChoiceTypeExtension.php
  src/Autocomplete/src/Form/WrappedEntityTypeAutocompleter.php
  src/Autocomplete/src/OptionsAwareEntityAutocompleterInterface.php
  src/Autocomplete/tests/Fixtures/Autocompleter/CustomGroupByProductAutocompleter.php
  src/Autocomplete/tests/Fixtures/Autocompleter/CustomProductAutocompleter.php
  src/Autocomplete/tests/Fixtures/Entity/Category.php
  src/Autocomplete/tests/Fixtures/Entity/Ingredient.php
  src/Autocomplete/tests/Fixtures/Entity/Product.php
  src/Autocomplete/tests/Fixtures/Factory/CategoryFactory.php
  src/Autocomplete/tests/Fixtures/Factory/IngredientFactory.php
  src/Autocomplete/tests/Fixtures/Factory/ProductFactory.php
  src/Autocomplete/tests/Fixtures/Form/AlternateRouteAutocompleteType.php
  src/Autocomplete/tests/Fixtures/Form/CategoryAutocompleteType.php
  src/Autocomplete/tests/Fixtures/Form/CategoryNoChoiceLabelAutocompleteType.php
  src/Autocomplete/tests/Fixtures/Form/IngredientAutocompleteType.php
  src/Autocomplete/tests/Fixtures/Form/ProductType.php
  src/Autocomplete/tests/Functional/AutocompleteFormRenderingTest.php
  src/Autocomplete/tests/Unit/Calculator/ChecksumCalculatorTest.php
Labels: Status: Reviewed, Feature

#1477 [Turbo] simplify returning entity class name
  src/Turbo/src/Doctrine/ClassUtil.php
Labels: Status: Needs Review

#1478 [StimulusBundle/TwigComponent] Fix "use_yield" to "true" deprecation notice in CI
  src/StimulusBundle/src/Helper/StimulusHelper.php
  src/StimulusBundle/tests/Dto/StimulusAttributesTest.php
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Needs Review

#1455 [CI] Fix RST Linter triggers
  .github/workflows/doctor-rst.yaml
Labels: Status: Reviewed

#1460 minor(live): add security tests
  src/LiveComponent/composer.json
  src/LiveComponent/tests/Fixtures/Component/WithSecurity.php
  src/LiveComponent/tests/Fixtures/Kernel.php
  src/LiveComponent/tests/Fixtures/templates/components/with_security.html.twig
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
Labels: Status: Needs Review

#1484 [Live] Fixed idiomorph id child handling & JavaScript cleanup
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/assets/dist/Component/ElementDriver.d.ts
  src/LiveComponent/assets/dist/Component/index.d.ts
  src/LiveComponent/assets/dist/Component/plugins/ChildComponentPlugin.d.ts
  src/LiveComponent/assets/dist/ComponentRegistry.d.ts
  src/LiveComponent/assets/dist/Util/getElementAsTagText.d.ts
  src/LiveComponent/assets/dist/dom_utils.d.ts
  src/LiveComponent/assets/dist/live_controller.d.ts
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/dist/morphdom.d.ts
  src/LiveComponent/assets/src/Component/ElementDriver.ts
  src/LiveComponent/assets/src/Component/index.ts
  src/LiveComponent/assets/src/Component/plugins/ChildComponentPlugin.ts
  src/LiveComponent/assets/src/Component/plugins/LoadingPlugin.ts
  src/LiveComponent/assets/src/ComponentRegistry.ts
  src/LiveComponent/assets/src/Util/getElementAsTagText.ts
  src/LiveComponent/assets/src/dom_utils.ts
  src/LiveComponent/assets/src/live_controller.ts
  src/LiveComponent/assets/src/morphdom.ts
  src/LiveComponent/assets/test/Component/index.test.ts
  src/LiveComponent/assets/test/ComponentRegistry.test.ts
  src/LiveComponent/assets/test/Util/getElementAsTagText.test.ts
  src/LiveComponent/assets/test/controller/basic.test.ts
  src/LiveComponent/assets/test/controller/child-model.test.ts
  src/LiveComponent/assets/test/controller/child.test.ts
  src/LiveComponent/assets/test/controller/emit.test.ts
  src/LiveComponent/assets/test/controller/loading.test.ts
  src/LiveComponent/assets/test/controller/model.test.ts
  src/LiveComponent/assets/test/controller/render.test.ts
  src/LiveComponent/assets/test/dom_utils.test.ts
  src/LiveComponent/assets/test/tools.ts
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/EventListener/InterceptChildComponentRenderSubscriber.php
  src/LiveComponent/src/Test/TestLiveComponent.php
  src/LiveComponent/src/Util/ChildComponentPartialRenderer.php
  src/LiveComponent/src/Util/LiveAttributesCollection.php
  src/LiveComponent/src/Util/LiveControllerAttributesCreator.php
  src/LiveComponent/tests/Fixtures/templates/components/todo_list.html.twig
  src/LiveComponent/tests/Functional/EventListener/AddLiveAttributesSubscriberTest.php
  src/LiveComponent/tests/Functional/EventListener/DeferLiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/EventListener/InterceptChildComponentRenderSubscriberTest.php
  src/LiveComponent/tests/Functional/LiveResponderTest.php
  src/LiveComponent/tests/Integration/EventListener/DataModelPropsSubscriberTest.php
  src/LiveComponent/tests/Integration/Twig/LiveComponentRuntimeTest.php
  src/LiveComponent/tests/LiveComponentTestHelper.php
  src/LiveComponent/tests/Unit/Util/LiveAttributesCollectionTest.php
  ux.symfony.com/templates/components/LiveMemory/Card.html.twig
  ux.symfony.com/templates/components/LiveMemory/Tableau.html.twig
Labels: Status: Needs Review

#1476 [Turbo] Allowing Turbo 8
  src/Turbo/assets/package.json
Labels: Status: Needs Review

#1486 [Twig][Live] Skip Twig 3.9 🚒 (do not set `use_yield = true` for now)
  src/LiveComponent/composer.json
  src/StimulusBundle/composer.json
  src/StimulusBundle/src/Helper/StimulusHelper.php
  src/StimulusBundle/tests/Dto/StimulusAttributesTest.php
  src/TwigComponent/composer.json
  src/TwigComponent/tests/Unit/ComponentAttributesTest.php
Labels: Status: Needs Review

#1485 [Docs] Fix a minor typo
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#1495 [Site] Leveraging Turbo 8 on ux.symfony.com
  ux.symfony.com/assets/controllers.json
  ux.symfony.com/importmap.php
  ux.symfony.com/templates/base.html.twig
Labels: Status: Needs Review

#1468 [Autocomplete] Add support for doctrine/orm:^3.0
  src/Autocomplete/CHANGELOG.md
  src/Autocomplete/composer.json
  src/Autocomplete/src/Doctrine/EntityMetadata.php
  src/Autocomplete/src/Doctrine/EntitySearchUtil.php
  src/Autocomplete/tests/Integration/Doctrine/EntityMetadataTest.php
Labels: Status: Needs Review

#1494 Bootstrapping an UPGRADE log
  UPGRADE.md
Labels: Status: Needs Review

#1497 Build reproductible TemplateMap
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/Twig/TemplateCacheWarmer.php
  src/LiveComponent/src/Twig/TemplateMap.php
  src/LiveComponent/tests/Unit/Twig/TemplateCacheWarmerTest.php
Labels: Status: Needs Review

#1501 [Live] Fixing bug where the active input would maintain its value, but lose its cursor position
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/package.json
  src/LiveComponent/assets/src/morphdom.ts
  src/LiveComponent/assets/test/controller/model.test.ts
  src/LiveComponent/assets/test/controller/render.test.ts
Labels: Bug, Status: Needs Review

#1502 [Autocomplete] Fix 2 bugs where TomSelect would reset when not necessary
  src/Autocomplete/assets/dist/controller.js
  src/Autocomplete/assets/src/controller.ts
  src/Autocomplete/assets/test/controller.test.ts
Labels: Status: Needs Review

#1503 [Twig][Live] Migrate PHPUnit configuration
  src/LiveComponent/phpunit.xml.dist
  src/TwigComponent/phpunit.xml.dist
Labels: Status: Needs Review

#1513 [Autocomplete] Fix regression where placeholder change didn't cause a reset
  src/Autocomplete/assets/dist/controller.js
  src/Autocomplete/assets/src/controller.ts
Labels: Status: Needs Review

#1517 [Site] Replace stimulus_* helpers with data-attributes
  ux.symfony.com/src/Model/RecipeFileTree.php
  ux.symfony.com/src/Util/SourceCleaner.php
  ux.symfony.com/templates/components/BootstrapModal.html.twig
  ux.symfony.com/templates/components/CodeBlock.html.twig
  ux.symfony.com/templates/components/CodeBlockButtons.html.twig
  ux.symfony.com/templates/components/DinoChart.html.twig
  ux.symfony.com/templates/components/HomepageTerminalSwapper.html.twig
  ux.symfony.com/templates/components/TerminalCommand.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
  ux.symfony.com/templates/ux_packages/lazy-image.html.twig
  ux.symfony.com/templates/ux_packages/swup.html.twig
  ux.symfony.com/templates/ux_packages/translator.html.twig
  ux.symfony.com/templates/ux_packages/typed.html.twig
  ux.symfony.com/tests/Unit/Util/SourceCleanerTest.php
Labels: Status: Reviewed

#1518 [Chart.js] Fix peerDepencies constraint
  src/Chartjs/assets/package.json
Labels: Status: Needs Review

#1521 Update AutocompleteBundle.de.php
  src/Autocomplete/translations/AutocompleteBundle.de.php
Labels: Status: Reviewed

#1510 [Site] Fix TomSelect select colors in dark mode
  ux.symfony.com/assets/styles/vendor/_tom-select.scss
  ux.symfony.com/templates/liveDemoBase.html.twig
Labels: Status: Needs Review

#1524 2.15 CHANGELOG
  src/Autocomplete/CHANGELOG.md
  src/Chartjs/CHANGELOG.md
  src/LiveComponent/CHANGELOG.md
  src/Turbo/CHANGELOG.md
  src/TwigComponent/CHANGELOG.md
  ux.symfony.com/src/Util/SourceCleaner.php
Labels: Status: Needs Review

#1511 Update index.rst - updated the Livewire website link
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1461 feat(live): improve `TestLiveComponent::actingAs()`
  src/LiveComponent/src/Test/TestLiveComponent.php
  src/LiveComponent/tests/Fixtures/Kernel.php
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/Test/InteractsWithLiveComponentsTest.php
Labels: Status: Needs Review

#1443 [Translator] Update intl-messageformat range version to ^10.5.11, close #1437
  src/Translator/CHANGELOG.md
  src/Translator/assets/package.json
  src/Translator/assets/src/formatters/intl-formatter.ts
Labels: Status: Needs Review

#1436 [Twig][Live] Drop Twig 2 support
  src/LiveComponent/composer.json
  src/TwigComponent/composer.json
  src/TwigComponent/src/ComponentRenderer.php
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Status: Needs Review

#1431 [LiveComponent] Add better error message when hydrating dates
  src/LiveComponent/src/LiveComponentHydrator.php
  src/LiveComponent/tests/Integration/LiveComponentHydratorTest.php
Labels: Status: Needs Review

#1430 [LiveComponent] Fix component syntax error in doc
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1530 upgrading to latest ux 2.15.0
  ux.symfony.com/composer.lock
  ux.symfony.com/importmap.php
Labels: Status: Reviewed

#1534 upgrading mercure and specifying database options
  ux.symfony.com/mercure/.platform.app.yaml
Labels: Status: Needs Review

#1537 [Doc] Fix a minor syntax issue in docs
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed

#1539 [Doc] Reword the section about the locale in Live Components
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#1506 [Site] Clean LiveMemory styles
  ux.symfony.com/assets/styles/demos/_live-memory.scss
  ux.symfony.com/assets/styles/demos/live-memory.min.css
  ux.symfony.com/assets/styles/demos/live-memory/components/_Board.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Debug.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Logo.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_Score.scss
  ux.symfony.com/assets/styles/demos/live-memory/components/_ThemeSwitch.scss
  ux.symfony.com/src/LiveMemory/Asset/CssCompiler.php
Labels: Status: Needs Review

#1525 [LiveComponent] Store TemplateMap in `build_dir`
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/Twig/TemplateCacheWarmer.php
  src/LiveComponent/src/Twig/TemplateMap.php
Labels: Status: Reviewed

#1527 Update AutocompleteBundle.ar.php
  src/Autocomplete/translations/AutocompleteBundle.ar.php
Labels: Status: Needs Review

#1550 [CS] Minor CS fixes
  src/LiveComponent/src/Twig/TemplateCacheWarmer.php
  ux.symfony.com/src/LiveMemory/Asset/CssCompiler.php
Labels: Status: Needs Review

#1553 [Autocomplete] Remove `console.log` from controller
  src/Autocomplete/assets/dist/controller.js
  src/Autocomplete/assets/src/controller.ts
Labels: Status: Needs Review

#1551 [CI] Configure 'test' workflow to ignore doc updates
  .github/workflows/test.yaml
Labels: Status: Needs Review

#1549 [LiveComponent] Add doc about the placeholder macro
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1542 [LiveCollectionType] Fix inline rendering example
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#1545 Update error message with `php bin/console`
  src/StimulusBundle/src/AssetMapper/AutoImportLocator.php
Labels: Status: Reviewed

#1546 Update lazy-image.html.twig
  ux.symfony.com/templates/ux_packages/lazy-image.html.twig
Labels: Status: Reviewed

#1554 [LiveComponent] Fix doc
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#1548 [Live] Reverting ignoreActiveValue: true in Idiomorph
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Component/UnsyncedInputsTracker.ts
  src/LiveComponent/assets/src/morphdom.ts
  src/LiveComponent/assets/test/controller/render.test.ts
Labels: Status: Needs Review

#1535 Update AutocompleteBundle.tr.php
  src/Autocomplete/translations/AutocompleteBundle.tr.php
Labels: Status: Needs Review

#1519 [Translator] Clean code to suppress warnings
  src/Translator/assets/dist/translator_controller.js
  src/Translator/assets/src/formatters/formatter.ts
  src/Translator/assets/src/translator.ts
Labels: Status: Reviewed

#1538 [Doc] Add more examples of adding attributes in Live Components
  src/LiveComponent/doc/index.rst
Labels: Status: Reviewed

#1416 Introduce CVA to style TwigComponent
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
  src/TwigComponent/src/CVA.php
  src/TwigComponent/src/Twig/ComponentExtension.php
  src/TwigComponent/tests/Fixtures/templates/class_merge.html.twig
  src/TwigComponent/tests/Fixtures/templates/components/Alert.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
  src/TwigComponent/tests/Unit/CVATest.php
Labels: Status: Reviewed, Feature

#1552 [TwigComponent] Fix full context is stored in profiler
  src/TwigComponent/src/DataCollector/TwigComponentDataCollector.php
Labels: Status: Needs Review

#1559 Prepping 2.16 changelogs
  UPGRADE.md
  src/Autocomplete/CHANGELOG.md
  src/LiveComponent/CHANGELOG.md
  src/Translator/CHANGELOG.md
  src/TwigComponent/CHANGELOG.md
Labels: Status: Needs Review
