Repository symfony/ux, pull requests merged in 2024-05, with the labels that each got.

#1809 [Translator] Create valid constant names for keys starting with numeric chars
  src/Translator/src/TranslationsDumper.php
  src/Translator/tests/TranslationsDumperTest.php
Labels: Bug, Status: Reviewed

#1815 [Site] Some more cleaning
  ux.symfony.com/assets/styles/app.scss
  ux.symfony.com/assets/styles/app/_typography.scss
  ux.symfony.com/assets/styles/components/_DemoContainer.scss
  ux.symfony.com/assets/styles/components/_FileTree.scss
  ux.symfony.com/assets/styles/components/_demo-container.scss
  ux.symfony.com/assets/styles/utilities/_arrow.scss
  ux.symfony.com/assets/styles/utilities/_font.scss
  ux.symfony.com/assets/styles/utilities/_rich-text.scss
  ux.symfony.com/config/packages/twig.yaml
  ux.symfony.com/src/Controller/UxPackage/TurboController.php
  ux.symfony.com/src/Service/PackageContext.php
  ux.symfony.com/src/Service/TwigPackageHelper.php
  ux.symfony.com/templates/bundles/TwigBundle/Exception/error.html.twig
  ux.symfony.com/templates/changelog.html.twig
  ux.symfony.com/templates/components/Foo.html.twig
  ux.symfony.com/templates/components/PackageHeader.html.twig
  ux.symfony.com/templates/components/TestingAnonymous.html.twig
  ux.symfony.com/templates/demos/live_demo.html.twig
  ux.symfony.com/templates/icons/index.html.twig
  ux.symfony.com/templates/main/_file_tree.html.twig
  ux.symfony.com/templates/main/demos.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
  ux.symfony.com/templates/main/packages.html.twig
  ux.symfony.com/templates/ux_packages/_package_demo.html.twig
  ux.symfony.com/templates/ux_packages/turbo.html.twig
Labels: Status: Reviewed, Site

#1814 [Site] Add robots.txt & sitemap.xml
  ux.symfony.com/php.ini
  ux.symfony.com/src/Controller/MainController.php
  ux.symfony.com/src/Controller/SitemapController.php
  ux.symfony.com/templates/robots.txt.twig
  ux.symfony.com/templates/sitemap.xml.twig
  ux.symfony.com/tests/Functional/RobotsTest.php
  ux.symfony.com/tests/Functional/SitemapTest.php
Labels: Status: Reviewed, Site

#1813 [Site] Clean demos & packages pages
  ux.symfony.com/assets/controllers/code-expander-controller.js
  ux.symfony.com/assets/styles/components/_DemoCard.scss
  ux.symfony.com/assets/styles/components/_Terminal.scss
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/templates/_aside.html.twig
  ux.symfony.com/templates/components/CodeWithExplanationRow.html.twig
  ux.symfony.com/templates/main/demos.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
  ux.symfony.com/templates/main/packages.html.twig
Labels: Status: Reviewed, Site

#1821 [Site] Fix input range color
  ux.symfony.com/assets/styles/_variables.scss
Labels: Status: Reviewed, Site

#1827 [Site] Clean templates
  ux.symfony.com/assets/images/heart.png
  ux.symfony.com/assets/images/heart.webp
  ux.symfony.com/assets/styles/_container.scss
  ux.symfony.com/assets/styles/app/_html.scss
  ux.symfony.com/assets/styles/components/_Banner.scss
  ux.symfony.com/assets/styles/components/_DemoCard.scss
  ux.symfony.com/assets/styles/components/_DemoContainer.scss
  ux.symfony.com/assets/styles/sections/_hero.scss
  ux.symfony.com/assets/styles/sections/_nav.scss
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/src/Twig/CodeWithExplanationRow.php
  ux.symfony.com/src/Twig/Components/Code/CodeBlock.php
  ux.symfony.com/src/Twig/Components/Code/CodeWithExplanationRow.php
  ux.symfony.com/src/Twig/Components/Code/TabbedCodeBlocks.php
  ux.symfony.com/src/Twig/Components/Demo/PrevNextDemo.php
  ux.symfony.com/src/Twig/Components/Package/PackageBox.php
  ux.symfony.com/src/Twig/Components/Package/PackageHeader.php
  ux.symfony.com/src/Twig/Components/Package/SearchPackages.php
  ux.symfony.com/src/Twig/Extension/HighlightExtension.php
  ux.symfony.com/templates/_banner.html.twig
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/base.html.twig
  ux.symfony.com/templates/bundles/TwigBundle/Exception/error.html.twig
  ux.symfony.com/templates/changelog.html.twig
  ux.symfony.com/templates/components/Alert.html.twig
  ux.symfony.com/templates/components/Code/CodeBlock.html.twig
  ux.symfony.com/templates/components/Code/CodeBlockButtons.html.twig
  ux.symfony.com/templates/components/Code/CodeLine.html.twig
  ux.symfony.com/templates/components/Code/CodeWithExplanationRow.html.twig
  ux.symfony.com/templates/components/Code/TabbedCodeBlocks.html.twig
  ux.symfony.com/templates/components/Demo/DemoCard.html.twig
  ux.symfony.com/templates/components/Demo/PrevNext.html.twig
  ux.symfony.com/templates/components/Icon/IconModal.html.twig
  ux.symfony.com/templates/components/Icon/IconSearch.html.twig
  ux.symfony.com/templates/components/Icon/IconSetCard.html.twig
  ux.symfony.com/templates/components/InvoiceCreatorLineItem.html.twig
  ux.symfony.com/templates/components/NewProductForm.html.twig
  ux.symfony.com/templates/components/Package/PackageBox.html.twig
  ux.symfony.com/templates/components/Package/PackageHeader.html.twig
  ux.symfony.com/templates/components/Package/SearchPackages.html.twig
  ux.symfony.com/templates/components/SideBySideCodeRow.html.twig
  ux.symfony.com/templates/components/TodoListForm.html.twig
  ux.symfony.com/templates/demos/live_component/dependent_form_fields.html.twig
  ux.symfony.com/templates/demos/live_component/infinite_scroll.html.twig
  ux.symfony.com/templates/demos/live_component/invoice.html.twig
  ux.symfony.com/templates/demos/live_component/product_form.html.twig
  ux.symfony.com/templates/demos/live_component/voting.html.twig
  ux.symfony.com/templates/demos/live_demo.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Tableau.html.twig
  ux.symfony.com/templates/icons/index.html.twig
  ux.symfony.com/templates/main/_file_tree.html.twig
  ux.symfony.com/templates/main/demos.html.twig
  ux.symfony.com/templates/main/homepage.html.twig
  ux.symfony.com/templates/main/packages.html.twig
  ux.symfony.com/templates/ux_packages/live_component.html.twig
  ux.symfony.com/templates/ux_packages/package.html.twig
  ux.symfony.com/templates/ux_packages/translator/_translator_demo_block.html.twig
  ux.symfony.com/templates/ux_packages/turbo/_chatForm.html.twig
Labels: Status: Needs Review, Site

#1824 [Stimulus] Use Twig >3.9 'EscaperRuntime'
  src/StimulusBundle/src/Dto/StimulusAttributes.php
Labels: Status: Reviewed

#1823 [TwigComponent] Remove wrongly added configuration
  src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php
Labels: Bug, Status: Reviewed, TwigComponent

#1820 [TwigComponent] Allow input props to have the same name as context variables
  src/TwigComponent/src/ComponentRenderer.php
  src/TwigComponent/src/Twig/PropsNode.php
  src/TwigComponent/tests/Fixtures/templates/anonymous_component_with_input_prop_with_same_name_in_context.html.twig
  src/TwigComponent/tests/Integration/ComponentExtensionTest.php
Labels: Bug, Status: Reviewed, TwigComponent

#1831 [Site] Icons colors
  ux.symfony.com/assets/styles/components/_IconGrid.scss
  ux.symfony.com/assets/styles/components/_IconModal.scss
  ux.symfony.com/src/Controller/Icons/IconsController.php
  ux.symfony.com/src/Twig/Components/Icon/IconSearch.php
  ux.symfony.com/src/Twig/Components/Icon/IconSetCard.php
  ux.symfony.com/templates/components/Icon/IconGrid.html.twig
  ux.symfony.com/templates/components/Icon/IconModal.html.twig
  ux.symfony.com/templates/components/Icon/IconSearch.html.twig
Labels: Status: Needs Review, Site

#1832 [LiveComponent] add support for testing file uploads in actions
  src/LiveComponent/CHANGELOG.md
  src/LiveComponent/doc/index.rst
  src/LiveComponent/src/Test/TestLiveComponent.php
Labels: Status: Reviewed, Feature, LiveComponent

#1837 [Chartjs] Improve Y axis formatting example
  src/Chartjs/doc/index.rst
Labels: documentation, Status: Reviewed, Chartjs

#1845 [TwigComponent] Update DOC preMount validation data code
  src/TwigComponent/doc/index.rst
Labels: Status: Reviewed, LiveComponent

#1861 Fix InvoiceCreator demo
  ux.symfony.com/src/Twig/InvoiceCreator.php
Labels: Bug, Status: Reviewed

#1864 [Site] Add Icons package data
  ux.symfony.com/assets/images/ux_packages/icons.svg
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/config/bundles.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/symfony.lock
  ux.symfony.com/templates/icons/index.html.twig
  ux.symfony.com/tests/Functional/UxPackagesTest.php
Labels: Status: Needs Review, Site

#1863 [Site] CodeBlock with gutter and line pre-slice
  ux.symfony.com/assets/styles/components/_Terminal.scss
  ux.symfony.com/src/Twig/Components/Code/CodeBlock.php
  ux.symfony.com/src/Twig/Extension/HighlightExtension.php
  ux.symfony.com/templates/components/Code/CodeBlock.html.twig
Labels: Status: Needs Review, Feature, Site
