Repository symfony/ux, pull requests merged in 2024-06, with the labels that each got.

#1866 autocomplete: add slovak translations
  src/Autocomplete/translations/AutocompleteBundle.sk.php
Labels: Status: Reviewed

#1865 Use version instead of url in docs
  src/StimulusBundle/doc/index.rst
Labels: Bug, Status: Reviewed

#1877 [TwigComponent] Disable profiler integration via configuration
  src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php
  src/TwigComponent/tests/Unit/DependencyInjection/TwigComponentExtensionTest.php
Labels: Status: Needs Review, Feature, TwigComponent

#1878 Remove subtree splits check
  .github/sync-packages.php
  .github/workflows/package-tests.yml
  src/Autocomplete/.gitattributes
  src/Autocomplete/.github/PULL_REQUEST_TEMPLATE.md
  src/Autocomplete/.github/workflows/check-subtree-split.yml
  src/Chartjs/.gitattributes
  src/Chartjs/.github/PULL_REQUEST_TEMPLATE.md
  src/Chartjs/.github/workflows/check-subtree-split.yml
  src/Cropperjs/.gitattributes
  src/Cropperjs/.github/PULL_REQUEST_TEMPLATE.md
  src/Cropperjs/.github/workflows/check-subtree-split.yml
  src/Dropzone/.gitattributes
  src/Dropzone/.github/PULL_REQUEST_TEMPLATE.md
  src/Dropzone/.github/workflows/check-subtree-split.yml
  src/Icons/.gitattributes
  src/Icons/.github/PULL_REQUEST_TEMPLATE.md
  src/Icons/.github/workflows/check-subtree-split.yml
  src/LazyImage/.gitattributes
  src/LazyImage/.github/PULL_REQUEST_TEMPLATE.md
  src/LazyImage/.github/workflows/check-subtree-split.yml
  src/LiveComponent/.gitattributes
  src/LiveComponent/.github/PULL_REQUEST_TEMPLATE.md
  src/LiveComponent/.github/workflows/check-subtree-split.yml
  src/Notify/.gitattributes
  src/Notify/.github/PULL_REQUEST_TEMPLATE.md
  src/Notify/.github/workflows/check-subtree-split.yml
  src/React/.gitattributes
  src/React/.github/PULL_REQUEST_TEMPLATE.md
  src/React/.github/workflows/check-subtree-split.yml
  src/StimulusBundle/.gitattributes
  src/StimulusBundle/.github/PULL_REQUEST_TEMPLATE.md
  src/StimulusBundle/.github/workflows/check-subtree-split.yml
  src/Svelte/.gitattributes
  src/Svelte/.github/PULL_REQUEST_TEMPLATE.md
  src/Svelte/.github/workflows/check-subtree-split.yml
  src/Swup/.gitattributes
  src/Swup/.github/PULL_REQUEST_TEMPLATE.md
  src/Swup/.github/workflows/check-subtree-split.yml
  src/TogglePassword/.gitattributes
  src/TogglePassword/.github/PULL_REQUEST_TEMPLATE.md
  src/TogglePassword/.github/workflows/check-subtree-split.yml
  src/Translator/.gitattributes
  src/Translator/.github/PULL_REQUEST_TEMPLATE.md
  src/Translator/.github/workflows/check-subtree-split.yml
  src/Turbo/.gitattributes
  src/Turbo/.github/PULL_REQUEST_TEMPLATE.md
  src/Turbo/.github/workflows/check-subtree-split.yml
  src/TwigComponent/.gitattributes
  src/TwigComponent/.github/PULL_REQUEST_TEMPLATE.md
  src/TwigComponent/.github/workflows/check-subtree-split.yml
  src/Typed/.gitattributes
  src/Typed/.github/PULL_REQUEST_TEMPLATE.md
  src/Typed/.github/workflows/check-subtree-split.yml
  src/Vue/.gitattributes
  src/Vue/.github/PULL_REQUEST_TEMPLATE.md
  src/Vue/.github/workflows/check-subtree-split.yml
Labels: Status: Needs Review

#1874 Fix the example with Expression Language
  src/Turbo/doc/index.rst
Labels: Status: Needs Review

#1876 [LazyImage] Fix code block rendering in docs
  src/LazyImage/doc/index.rst
Labels: Status: Needs Review, LazyImage

#1888 [Site] Fix UX Icons color
  ux.symfony.com/src/Service/UxPackageRepository.php
Labels: Status: Needs Review, Site

#1887 [Demo] Infinite Scroll 2/2
  ux.symfony.com/assets/controllers/appear-controller.js
  ux.symfony.com/assets/images/live_demo/infinite-scroll-2.png
  ux.symfony.com/assets/images/live_demo/infinite-scroll.png
  ux.symfony.com/assets/styles/app/_typography.scss
  ux.symfony.com/assets/styles/components/_Browser.scss
  ux.symfony.com/assets/styles/components/_DemoContainer.scss
  ux.symfony.com/assets/styles/components/_ProductGrid.scss
  ux.symfony.com/assets/styles/layouts/_container.scss
  ux.symfony.com/assets/styles/layouts/_section.scss
  ux.symfony.com/src/Controller/Demo/LiveComponentDemoController.php
  ux.symfony.com/src/Service/EmojiCollection.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/src/Twig/Components/Code/CodeBlock.php
  ux.symfony.com/src/Twig/Components/Code/CodeWithExplanationRow.php
  ux.symfony.com/src/Twig/ProductGrid2.php
  ux.symfony.com/templates/components/Code/CodeBlock.html.twig
  ux.symfony.com/templates/components/Code/CodeBlockButtons.html.twig
  ux.symfony.com/templates/components/Code/CodeWithExplanationRow.html.twig
  ux.symfony.com/templates/components/Demo/PrevNext.html.twig
  ux.symfony.com/templates/components/ProductGrid.html.twig
  ux.symfony.com/templates/components/ProductGrid2.html.twig
  ux.symfony.com/templates/demos/live_component/bootstrap.html.twig
  ux.symfony.com/templates/demos/live_component/infinite_scroll.html.twig
  ux.symfony.com/templates/demos/live_component/infinite_scroll_2.html.twig
  ux.symfony.com/templates/demos/live_demo.html.twig
Labels: Status: Needs Review, demo

#1882 [TwigComponent] Restrict anonymous component lookup to Twig files in debug command
  src/TwigComponent/src/Command/TwigComponentDebugCommand.php
  src/TwigComponent/tests/Fixtures/templates/components/NotAComponent.md
  src/TwigComponent/tests/Integration/Command/TwigComponentDebugCommandTest.php
Labels: Bug, Status: Reviewed, TwigComponent

#1885 [Icons] Document http-client requirement
  src/Icons/doc/index.rst
Labels: Status: Needs Review, Icons

#1893 Revert #1694 "[LiveComponent] set LiveArg value to null if empty string"
  src/LiveComponent/src/Attribute/LiveArg.php
  src/LiveComponent/src/DependencyInjection/LiveComponentExtension.php
  src/LiveComponent/src/EventListener/LiveComponentSubscriber.php
  src/LiveComponent/src/Util/LiveRequestDataParser.php
  src/LiveComponent/src/ValueResolver/LiveArgValueResolver.php
  src/LiveComponent/src/ValueResolver/LiveArgValueResolverTrait.php
  src/LiveComponent/tests/Fixtures/Component/Component6.php
  src/LiveComponent/tests/Fixtures/templates/components/component6.html.twig
  src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/Test/InteractsWithLiveComponentsTest.php
Labels: Bug, Status: Needs Review, LiveComponent

#1898 [Icons] Update composer
  src/Icons/composer.json
Labels: Status: Reviewed, Icons

#1911 [TwigComponent][Fix] Revert throwing exception when public property is unitialized
  src/TwigComponent/src/ComponentRenderer.php
Labels: Status: Needs Review, TwigComponent

#1910 [Docs][Stimulus] use camelCase for target naming
  src/StimulusBundle/doc/index.rst
Labels: Status: Reviewed

#1908 [Fix] Revert removing `twig_component.controllers_json`
  src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php
  src/TwigComponent/tests/Unit/DependencyInjection/TwigComponentExtensionTest.php
Labels: Bug, Status: Reviewed

#1904 [Translator] Fix changing dump directory using AssetMapper
  src/Translator/doc/index.rst
  src/Translator/src/DependencyInjection/UxTranslatorExtension.php
Labels: Bug, Status: Reviewed

#1903 [LiveComponent] accept live component Content-Type with suffix
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Component/index.ts
Labels: Bug, Status: Needs Review, LiveComponent

#1913 [Translator] Revert Fix changing dump directory using AssetMapper
  src/Translator/doc/index.rst
  src/Translator/src/DependencyInjection/UxTranslatorExtension.php
Labels: Bug, Status: Reviewed

#1907 [Site] Social metadata
  ux.symfony.com/assets/icons/hugeicons/new-twitter.svg
  ux.symfony.com/assets/images/icons/x-twitter.svg
  ux.symfony.com/assets/images/live_demo/auto-validating-form-1280x720.png
  ux.symfony.com/assets/images/live_demo/chartjs-1280x720.png
  ux.symfony.com/assets/images/live_demo/dependent-form-fields-1280x720.png
  ux.symfony.com/assets/images/live_demo/dependent-form-fields.png
  ux.symfony.com/assets/images/live_demo/form-collection-type-1280x720.png
  ux.symfony.com/assets/images/live_demo/form-collection-type.png
  ux.symfony.com/assets/images/live_demo/infinite-scroll-1280x720.png
  ux.symfony.com/assets/images/live_demo/infinite-scroll-2-1280x720.png
  ux.symfony.com/assets/images/live_demo/infinite-scroll-2.png
  ux.symfony.com/assets/images/live_demo/infinite-scroll.png
  ux.symfony.com/assets/images/live_demo/inline-edit-1280x720.png
  ux.symfony.com/assets/images/live_demo/inline-edit.png
  ux.symfony.com/assets/images/live_demo/invoice-1280x720.png
  ux.symfony.com/assets/images/live_demo/invoice.png
  ux.symfony.com/assets/images/live_demo/live-memory-1280x720.png
  ux.symfony.com/assets/images/live_demo/live-memory.png
  ux.symfony.com/assets/images/live_demo/product-form-1280x720.png
  ux.symfony.com/assets/images/live_demo/upload-1280x720.png
  ux.symfony.com/assets/images/live_demo/upload.png
  ux.symfony.com/assets/images/live_demo/voting-1280x720.png
  ux.symfony.com/assets/images/live_demo/voting.png
  ux.symfony.com/assets/styles/sections/_nav.scss
  ux.symfony.com/composer.lock
  ux.symfony.com/src/Model/LiveDemo.php
  ux.symfony.com/templates/_header.html.twig
  ux.symfony.com/templates/_meta.html.twig
  ux.symfony.com/templates/base.html.twig
  ux.symfony.com/templates/demos/live_demo.html.twig
  ux.symfony.com/templates/demos/live_memory/index.html.twig
Labels: Status: Needs Review, Site

#1918 [Site] Improve social meta
  ux.symfony.com/assets/images/ux_packages/autocomplete-1200x675.png
  ux.symfony.com/assets/images/ux_packages/chartsjs-1200x675.png
  ux.symfony.com/assets/images/ux_packages/cropper-1200x675.png
  ux.symfony.com/assets/images/ux_packages/dropzone-1200x675.png
  ux.symfony.com/assets/images/ux_packages/form-collection.png
  ux.symfony.com/assets/images/ux_packages/lazy-image-1200x675.png
  ux.symfony.com/assets/images/ux_packages/live-component-1200x675.png
  ux.symfony.com/assets/images/ux_packages/norify-1200x675.png
  ux.symfony.com/assets/images/ux_packages/react-1200x675.png
  ux.symfony.com/assets/images/ux_packages/svelte-1200x675.png
  ux.symfony.com/assets/images/ux_packages/swup-1200x675.png
  ux.symfony.com/assets/images/ux_packages/toggle-password-1200x675.png
  ux.symfony.com/assets/images/ux_packages/translator-1200x675.png
  ux.symfony.com/assets/images/ux_packages/turbo-1200x675.png
  ux.symfony.com/assets/images/ux_packages/twig-component-1200x675.png
  ux.symfony.com/assets/images/ux_packages/typed-1200x675.png
  ux.symfony.com/assets/images/ux_packages/ux-icons-1200x675.png
  ux.symfony.com/assets/images/ux_packages/vue-1200x675.png
  ux.symfony.com/src/Model/UxPackage.php
  ux.symfony.com/src/Service/LiveDemoRepository.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/templates/_meta.html.twig
  ux.symfony.com/templates/demos/live_demo.html.twig
  ux.symfony.com/templates/demos/live_memory/index.html.twig
  ux.symfony.com/templates/ux_packages/package.html.twig
Labels: Status: Needs Review, Site

#1919 [Site] Fix package meta
  ux.symfony.com/assets/images/ux_packages/chartjs-1200x675.png
  ux.symfony.com/assets/images/ux_packages/cropperjs-1200x675.png
  ux.symfony.com/assets/images/ux_packages/icons-1200x675.png
  ux.symfony.com/assets/images/ux_packages/notify-1200x675.png
  ux.symfony.com/src/Controller/Icons/IconsController.php
  ux.symfony.com/src/Model/UxPackage.php
  ux.symfony.com/src/Service/UxPackageRepository.php
  ux.symfony.com/templates/icons/index.html.twig
  ux.symfony.com/templates/ux_packages/package.html.twig
Labels: Status: Needs Review, Site

#1939 [Site] Fix translator social card
  ux.symfony.com/assets/images/ux_packages/translator-1200x675.png
Labels: Status: Reviewed, Site

#1929 [Turbo] Fix Doctrine Proxy are not Broadcasted
  src/Turbo/CHANGELOG.md
  src/Turbo/src/Doctrine/ClassUtil.php
  src/Turbo/tests/BroadcastTest.php
Labels: Bug, Status: Needs Review, Turbo

#1933 [Site] Fix Turbo demos
  ux.symfony.com/src/Controller/UxPackage/TurboController.php
  ux.symfony.com/templates/ux_packages/turbo/add_todo.html.twig
  ux.symfony.com/templates/ux_packages/turbo/todos.html.twig
Labels: Status: Needs Review, Site

#1935 [Site] Apply twig-cs-fixer
  ux.symfony.com/.twig-cs-fixer.dist.php
  ux.symfony.com/templates/components/Icon.html.twig
  ux.symfony.com/templates/components/Icon/IconModal.html.twig
  ux.symfony.com/templates/components/RegistrationForm.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Timer.html.twig
Labels: Status: Needs Review, Site

#1940 [TwigComponent] Ignore array|sequence in exception message
  src/TwigComponent/tests/Integration/EmbeddedComponentTest.php
Labels: Status: Reviewed, TwigComponent

#1828 [LiveComponent] Tokenize classes on all allowed whitespaces
  src/LiveComponent/assets/dist/live_controller.js
  src/LiveComponent/assets/src/Rendering/ExternalMutationTracker.ts
  src/LiveComponent/assets/test/Rendering/ExternalMutationTracker.test.ts
Labels: Bug, Status: Reviewed, LiveComponent

#1938 Remove declare_strict type
  src/Autocomplete/src/Checksum/ChecksumCalculator.php
  src/Autocomplete/tests/Unit/Calculator/ChecksumCalculatorTest.php
  src/LiveComponent/src/EventListener/DeferLiveComponentSubscriber.php
  src/LiveComponent/src/Util/FingerprintCalculator.php
  src/LiveComponent/src/Util/LiveComponentStack.php
  src/LiveComponent/tests/Fixtures/Component/DeferredComponent.php
  src/LiveComponent/tests/Fixtures/Component/DeferredComponentWithPlaceholder.php
  src/LiveComponent/tests/Fixtures/Component/TallyComponent.php
  src/LiveComponent/tests/Fixtures/Form/BlogPostFormLiveCollectionType.php
  src/LiveComponent/tests/Fixtures/Form/BlogPostFormType.php
  src/LiveComponent/tests/Fixtures/Form/CommentFormType.php
  src/LiveComponent/tests/Fixtures/Form/FormWithManyDifferentFieldsType.php
  src/LiveComponent/tests/Functional/EventListener/DeferLiveComponentSubscriberTest.php
  src/LiveComponent/tests/Functional/Form/ComponentWithFormTest.php
  src/LiveComponent/tests/Functional/ValidatableComponentTraitTest.php
  src/LiveComponent/tests/Unit/Form/ComponentWithFormTest.php
  src/StimulusBundle/config/services.php
  src/StimulusBundle/src/DependencyInjection/StimulusExtension.php
  src/StimulusBundle/src/Dto/StimulusAttributes.php
  src/StimulusBundle/src/Helper/StimulusHelper.php
  src/StimulusBundle/src/Twig/StimulusTwigExtension.php
  src/StimulusBundle/src/Twig/UxControllersTwigExtension.php
  src/StimulusBundle/tests/Dto/StimulusAttributesTest.php
  src/StimulusBundle/tests/Helper/StimulusHelperTest.php
  src/StimulusBundle/tests/StimulusIntegrationTestKernel.php
  src/StimulusBundle/tests/Twig/StimulusTwigExtensionTest.php
  src/TogglePassword/src/DependencyInjection/TogglePasswordExtension.php
  src/TogglePassword/src/Form/TogglePasswordTypeExtension.php
  src/TogglePassword/src/TogglePasswordBundle.php
  src/TogglePassword/tests/Form/TogglePasswordTypeTest.php
  src/TogglePassword/tests/TogglePasswordBundleTest.php
Labels: Status: Reviewed

#1921 [Live] Fix typing for loading hooks + HookManager
  src/LiveComponent/assets/dist/Component/index.d.ts
  src/LiveComponent/assets/dist/HookManager.d.ts
  src/LiveComponent/assets/src/Component/index.ts
  src/LiveComponent/assets/src/HookManager.ts
Labels: Bug, Status: Reviewed

#1936 [Site] Use ux-icons (1/2)
  ux.symfony.com/assets/icons/arrow-down.svg
  ux.symfony.com/assets/icons/arrow-left.svg
  ux.symfony.com/assets/icons/arrow-right.svg
  ux.symfony.com/assets/icons/arrow-up.svg
  ux.symfony.com/assets/icons/book-text.svg
  ux.symfony.com/assets/icons/chevron-down.svg
  ux.symfony.com/assets/icons/circle-check.svg
  ux.symfony.com/assets/icons/circle-exclamation.svg
  ux.symfony.com/assets/icons/circle-fill.svg
  ux.symfony.com/assets/icons/circle-help.svg
  ux.symfony.com/assets/icons/comment.svg
  ux.symfony.com/assets/icons/copy.svg
  ux.symfony.com/assets/icons/cross.svg
  ux.symfony.com/assets/icons/folder-open.svg
  ux.symfony.com/assets/icons/folder.svg
  ux.symfony.com/assets/icons/github.svg
  ux.symfony.com/assets/icons/grid-large.svg
  ux.symfony.com/assets/icons/grid-small.svg
  ux.symfony.com/assets/icons/heart.svg
  ux.symfony.com/assets/icons/icon-folder-plus.svg
  ux.symfony.com/assets/icons/icon-folder.svg
  ux.symfony.com/assets/icons/icon-search.svg
  ux.symfony.com/assets/icons/icon-sets.svg
  ux.symfony.com/assets/icons/icon-size.svg
  ux.symfony.com/assets/icons/icon-style.svg
  ux.symfony.com/assets/icons/icon-tag.svg
  ux.symfony.com/assets/icons/lock.svg
  ux.symfony.com/assets/icons/menu.svg
  ux.symfony.com/assets/icons/pencil.svg
  ux.symfony.com/assets/icons/plus.svg
  ux.symfony.com/assets/icons/refresh.svg
  ux.symfony.com/assets/icons/spinner.svg
  ux.symfony.com/assets/icons/support.svg
  ux.symfony.com/assets/icons/symfony.svg
  ux.symfony.com/assets/icons/symfonycast.svg
  ux.symfony.com/assets/icons/theme-dark.svg
  ux.symfony.com/assets/icons/theme-light.svg
  ux.symfony.com/assets/icons/theme-switcher.svg
  ux.symfony.com/assets/icons/twitter.svg
  ux.symfony.com/assets/icons/x-twitter.svg
  ux.symfony.com/assets/icons/x.svg
  ux.symfony.com/assets/styles/components/_DocsLink.scss
  ux.symfony.com/composer.lock
  ux.symfony.com/src/LiveMemory/Component/Icon.php
  ux.symfony.com/src/Twig/Icon.php
  ux.symfony.com/templates/components/Icon.html.twig
  ux.symfony.com/templates/demos/live_memory/components/LiveMemory/Icon.html.twig
Labels: Status: Reviewed, Site

#1931 [Turbo] Modernize code (ppp, types..)
  src/Turbo/src/Attribute/Broadcast.php
  src/Turbo/src/Bridge/Mercure/Broadcaster.php
  src/Turbo/src/Bridge/Mercure/TurboStreamListenRenderer.php
  src/Turbo/src/Broadcaster/IdAccessor.php
  src/Turbo/src/Broadcaster/ImuxBroadcaster.php
  src/Turbo/src/Broadcaster/TwigBroadcaster.php
  src/Turbo/src/Doctrine/BroadcastListener.php
  src/Turbo/src/Twig/TwigExtension.php
Labels: Status: Needs Review, Turbo
