Repository symfony/ux, pull requests merged in 2025-09, with the labels that each got.

#3056 [UX3] Start an UPGRADE file
  UPGRADE-3.0.md
  src/LiveComponent/CHANGELOG.md
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/doc/index.rst
Labels: docs, Status: Needs Review

#3072 Small update to explicit custom template path on components
  src/LiveComponent/doc/index.rst
Labels: Status: Needs Review

#3069 Fix Route PHP attribute in Vue Router Web History mode
  src/Vue/doc/index.rst
Labels: docs, Status: Reviewed

#3073 [Toolkit][Shadcn] Add AlertDialog recipe
  .github/workflows/unit-tests.yaml
  src/Toolkit/kits/shadcn/AlertDialog/EXAMPLES.md
  src/Toolkit/kits/shadcn/AlertDialog/assets/controllers/alert_dialog_controller.js
  src/Toolkit/kits/shadcn/AlertDialog/manifest.json
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Action.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Cancel.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Content.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Description.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Footer.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Header.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Title.html.twig
  src/Toolkit/kits/shadcn/AlertDialog/templates/components/AlertDialog/Trigger.html.twig
  src/Toolkit/kits/shadcn/manifest.json
  src/Toolkit/src/Command/InstallCommand.php
  src/Toolkit/src/Kit/KitContextRunner.php
  src/Toolkit/tests/Command/DebugKitCommandTest.php
  src/Toolkit/tests/Command/InstallCommandTest.php
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component AlertDialog, code 1__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component AlertDialog, code 2__1.html
  ux.symfony.com/assets/toolkit-shadcn.js
  ux.symfony.com/config/packages/asset_mapper.yaml
  ux.symfony.com/importmap.php
  ux.symfony.com/src/Service/Toolkit/ToolkitService.php
Labels: Status: Needs Review, Feature, Toolkit

#3083 Prevent pnpm to install new packages published the same day
  package.json
  pnpm-workspace.yaml
Labels: Status: Needs Review

#3084 [Site] Lock icons
  ux.symfony.com/assets/icons/bi/stars.svg
  ux.symfony.com/assets/icons/flowbite/users-group-solid.svg
  ux.symfony.com/assets/icons/logos/slack-icon.svg
  ux.symfony.com/assets/icons/lucide/book.svg
  ux.symfony.com/assets/icons/lucide/monitor-check.svg
  ux.symfony.com/assets/icons/lucide/package.svg
  ux.symfony.com/assets/icons/mdi/book-open-variant-outline.svg
  ux.symfony.com/assets/icons/raphael/help.svg
Labels: Bug, Status: Reviewed, Site

#3086 Add doc for E2E steps + minor modifications
  CONTRIBUTING.md
  bin/test_package.sh
  playwright.config.base.ts
  src/Autocomplete/assets/package.json
  src/Chartjs/assets/package.json
  src/Cropperjs/assets/package.json
  src/Dropzone/assets/package.json
  src/LiveComponent/assets/package.json
  src/Map/src/Bridge/Google/assets/package.json
  src/Map/src/Bridge/Leaflet/assets/package.json
  src/Notify/assets/package.json
  src/React/assets/package.json
  src/Svelte/assets/package.json
  src/Translator/assets/package.json
  src/Turbo/assets/package.json
  src/Vue/assets/package.json
Labels: docs, Status: Needs Review

#2671 [Icons] explain svg colors and improve example configuration
  src/Icons/doc/index.rst
Labels: docs, Icons

#3090 Refactor "test_package.sh" to its original purpose, add multiples checks for packages definition
  .github/workflows/code-quality.yaml
  bin/unit_test_package.sh
  src/Autocomplete/assets/package.json
  src/Chartjs/assets/package.json
  src/Cropperjs/assets/package.json
  src/Dropzone/assets/package.json
  src/LazyImage/assets/package.json
  src/LiveComponent/assets/package.json
  src/Map/assets/package.json
  src/Map/src/Bridge/Google/assets/package.json
  src/Map/src/Bridge/Leaflet/assets/package.json
  src/Notify/assets/package.json
  src/React/assets/package.json
  src/StimulusBundle/assets/package.json
  src/Svelte/assets/package.json
  src/Swup/assets/package.json
  src/Swup/composer.json
  src/TogglePassword/assets/package.json
  src/Toolkit/composer.json
  src/Translator/assets/package.json
  src/Turbo/assets/package.json
  src/Typed/assets/package.json
  src/Vue/assets/package.json
Labels: Status: Needs Review

#3093 [Site] Fix port to 9044 and upgrade UX dependencies
  ux.symfony.com/.symfony.local.yaml
  ux.symfony.com/.twig-cs-fixer.dist.php
  ux.symfony.com/composer.json
  ux.symfony.com/composer.lock
  ux.symfony.com/importmap.php
  ux.symfony.com/templates/components/Button.html.twig
  ux.symfony.com/templates/components/Table.html.twig
Labels: Bug, Status: Needs Review, Site

#3097 [Toolkit] Delay/hide the "Community Kits" feature, minor fixes
  src/Toolkit/README.md
  src/Toolkit/doc/index.rst
  src/Toolkit/kits/shadcn/AlertDialog/manifest.json
  src/Toolkit/kits/shadcn/AspectRatio/manifest.json
  src/Toolkit/kits/shadcn/INSTALL.md
  src/Toolkit/src/Command/InstallCommand.php
  src/Toolkit/tests/Command/InstallCommandTest.php
  src/Toolkit/tests/Functional/ComponentsRenderingTest.php
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Alert Dialog, code 1__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Alert Dialog, code 2__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Alert, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Aspect Ratio, code 1__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Aspect Ratio, code 2__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Aspect Ratio, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Avatar, code 4__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Badge, code 6__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Breadcrumb, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Button, code 11__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Card, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Checkbox, code 4__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Input, code 6__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Label, code 4__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Pagination, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Progress, code 4__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Select, code 4__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Separator, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Skeleton, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Switch, code 3__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Table, code 2__1.html
  src/Toolkit/tests/Functional/__snapshots__/ComponentsRenderingTest__testComponentRendering with data set Kit shadcn, component Textarea, code 4__1.html
  ux.symfony.com/assets/styles/components/_SidebarNav.scss
  ux.symfony.com/src/Controller/Toolkit/ComponentsController.php
  ux.symfony.com/src/LiveMemory/GameLevels.php
  ux.symfony.com/templates/ux_packages/toolkit.html.twig
Labels: Bug, Status: Needs Review, Toolkit

#3102 [Chartjs][Notify][React][Svelte] Remove StimulusHelper deprecation for 3.0
  src/Chartjs/CHANGELOG.md
  src/Chartjs/src/Twig/ChartExtension.php
  src/Notify/CHANGELOG.md
  src/Notify/src/Twig/NotifyRuntime.php
  src/React/CHANGELOG.md
  src/React/src/Twig/ReactComponentExtension.php
  src/Svelte/CHANGELOG.md
  src/Svelte/src/Twig/SvelteComponentExtension.php
  src/Vue/src/Twig/VueComponentExtension.php
Labels: Status: Needs Review, Feature, Chartjs, Notify, React, Svelte

#3105 [TwigComponent] Remove dev-dependency on WebpackEncoreBundle
  src/TwigComponent/CHANGELOG.md
  src/TwigComponent/composer.json
Labels: Bug, Status: Needs Review, TwigComponent

#3106 Remove explicit configuration `twig.exception_controller` from Kernel for testing
  src/Chartjs/tests/Kernel/TwigAppKernel.php
  src/Cropperjs/tests/Kernel/TwigAppKernel.php
  src/Dropzone/tests/Kernel/TwigAppKernel.php
  src/LazyImage/tests/Kernel/TwigAppKernel.php
  src/Map/tests/Kernel/TwigAppKernel.php
  src/Map/tests/Kernel/TwigComponentKernel.php
  src/Notify/tests/Kernel/TwigAppKernel.php
  src/React/tests/Kernel/TwigAppKernel.php
  src/Svelte/tests/Kernel/TwigAppKernel.php
  src/TogglePassword/tests/Kernel/TwigAppKernel.php
  src/Vue/tests/Kernel/TwigAppKernel.php
Labels: Bug, Status: Needs Review

#3082 [Icons] Add documentation on icons colors
  src/Icons/doc/index.rst
Labels: Documentation, Status: Reviewed, Icons
